// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! `vw cosim init` — a Rust cosim testbench.
//!
//! The design entity is the top level. nvc elaborates it as it stands and
//! loads a `cdylib` beside it; that library reaches the entity's ports over
//! VHPI and drives them, clock included. There is no VHDL harness — a
//! passthrough wrapper would only be a second copy of the port list to keep
//! in step with the design.
//!
//! What that leaves is a crate, a `build.rs` that finds the GPI libraries, a
//! `cosim.toml` saying which entity, and a registration in the bench cargo
//! workspace. All of it is written here.
//!
//! ## Reaching the ports
//!
//! A record port is not a value in itself — reading the aggregate handle is
//! a category error, and the GPI layer crashes rather than saying so — but
//! its elements are. So a record port becomes one handle per element,
//! `bus_in.go` reached as `dut.get_child("bus_in")?.get_child("go")?`, and
//! nested records are followed down.
//!
//! Subtypes need no special handling at all, as long as nothing is assumed
//! about width at generation time: a signal knows its own, so everything the
//! driver writes is sized from `get_range()` rather than from the type it was
//! declared with. That also makes a port whose width comes from a generic
//! work without the generic being mentioned.
//!
//! What is left over is genuinely awkward and is reported rather than
//! guessed at: an `integer`/`natural` port reads back as an empty bit string,
//! and an array-of-composite has no single bit string that means anything.
//! Both get a handle, and a note saying so.
//!
//! ## What is generated and what is yours
//!
//! `src/generated.rs` is rewritten every time — by `vw cosim init` and before
//! every run — and holds everything derived from the design: the handles, the
//! structs, the entry point. `src/lib.rs` holds `test()` and is written once.
//!
//! That split is what lets a bench grow. A design like a full FPGA top level
//! gets a Rust stand-in for one piece of hard IP at a time, and adding the
//! second must not cost the test written against the first. So `init` is
//! re-runnable: it takes what `cosim.toml` already says, adds whatever the
//! command line asked for, and regenerates. A design change can still break
//! the build — a port that went away takes its handle with it — but it breaks
//! visibly, at compile time, rather than by silently not being there.

use camino::{Utf8Path, Utf8PathBuf};
use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use super::entity::{DesignTypes, EntityInterface, Instance, Interface, Reach};
use super::{write_file, write_new_file, Created};
use crate::{Result, VhdlStandard, VwError};

/// The link flags every cosim crate needs, and the only thing in one.
///
/// Regenerated rather than checked in: it is identical in every bench, it is
/// derived from where `rust-cosim` put its GPI libraries, and a bench whose
/// copy has gone missing or gone stale fails at link time with an error that
/// says nothing about any of that. `vw bench run` rewrites it for every cosim
/// crate before building, so there is no state to keep in step.
const BUILD_RS: &str = r#"// Auto-generated by vw — safe to regenerate, and regenerated by `vw bench run`.
//
// A cosim testbench is a cdylib the simulator dlopens, so it has to be linked
// against the GPI libraries `rust-cosim` builds. `rust-cosim` declares
// `links = "cocotb"` and publishes their location as `DEP_COCOTB_TARGET_DIR`,
// which cargo hands to its dependents' build scripts — this one.
use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let libs_dir = PathBuf::from(env::var("DEP_COCOTB_TARGET_DIR").expect(
        "DEP_COCOTB_TARGET_DIR is not set — rust-cosim must be a dependency \
         of this crate",
    ));

    if !libs_dir.exists() {
        panic!(
            "the cocotb GPI libraries are not at {}.\n\
             Build rust-cosim first, or run this through `vw bench run`.",
            libs_dir.display(),
        );
    }

    let libs_dir = libs_dir.to_str().expect("GPI library path is not UTF-8");

    println!("cargo:rustc-link-arg=-L{libs_dir}");
    println!("cargo:rustc-link-arg=-lgpi");
    println!("cargo:rustc-link-arg=-lcocotbvhpi_nvc");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{libs_dir}");

    // `vhpi_assert` is the simulator's, resolved when nvc dlopens this. A
    // Linux shared library links with it undefined; the macOS linker refuses
    // to unless told that is the intent.
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-arg=-Wl,-undefined,dynamic_lookup");
    }
}
"#;

/// The first line of a `build.rs` this wrote, and the only thing that makes
/// it safe to rewrite one.
const BUILD_RS_MARKER: &str = "// Auto-generated by vw";

/// What a cosim bench ignores.
const GITIGNORE: &str = "\
# Auto-generated by vw and rewritten before every run — not worth committing.
build.rs
src/generated.rs

/target/
";

/// Create a Rust cosim testbench, or bring an existing one up to date.
///
/// Re-runnable on purpose. `cosim.toml` is the record of what this bench is —
/// which entity, which instances the driver stands in for — and this reads
/// it, folds in whatever the command line added, writes it back and
/// regenerates. What is regenerated is only ever `src/generated.rs`; the
/// test in `src/lib.rs` is written once and then left alone.
#[allow(clippy::too_many_arguments)]
pub fn init(
    workspace_dir: &Utf8Path,
    name: &str,
    dut: Option<&str>,
    components: &[String],
    vhdl_std: VhdlStandard,
) -> Result<Created> {
    // The name is a directory and a crate name, never a VHDL entity — the
    // entity is the design's — so it is as free as a mixed-signal bench's.
    super::check_crate_name(name)?;

    let bench_dir = workspace_dir.join("bench").join(name);
    let config_path = bench_dir.join("cosim.toml");
    let existing = config_path
        .exists()
        .then(|| crate::cosim::read_config(config_path.as_std_path()))
        .transpose()?;

    // A directory that is not a cosim bench is somebody else's; only one this
    // command made is one it may add to.
    if existing.is_none() {
        super::check_available(&bench_dir)?;
    }

    let config = merge_config(name, existing.as_ref(), dut, components)?;
    let updating = existing.is_some();

    let mut files = super::workspace::ensure_bench_workspace(workspace_dir)?;
    std::fs::create_dir_all(bench_dir.join("src").as_std_path())?;

    // Written from the merged config rather than the flags, so what is on
    // disk always says what the bench is.
    let dut_interface = resolve(workspace_dir, &config, vhdl_std)?;
    if write_file(&config_path, &render_config(name, &config, &dut_interface))?
    {
        files.push(config_path);
    }

    if !updating {
        let manifest = bench_dir.join("Cargo.toml");
        write_new_file(&manifest, &render_manifest(name))?;
        files.push(manifest);

        // Written once and then yours. Everything the design decides lives
        // next door in `generated.rs`, so this never has to be rewritten.
        let lib = bench_dir.join("src").join("lib.rs");
        write_new_file(&lib, &render_lib(&config))?;
        files.push(lib);
    }

    files.extend(ensure_generated(&bench_dir, &dut_interface)?);
    files.extend(ensure_scaffold(&bench_dir)?);

    let registered = super::workspace::register_member(workspace_dir, name)?;

    Ok(Created {
        name: name.to_string(),
        files,
        registered,
        updated: updating,
        next_steps: next_steps(
            name,
            &config,
            &dut_interface,
            updating,
            &bench_dir,
        ),
    })
}

/// What the bench is, after the command line has had its say.
fn merge_config(
    name: &str,
    existing: Option<&crate::cosim::CosimConfig>,
    dut: Option<&str>,
    components: &[String],
) -> Result<crate::cosim::CosimConfig> {
    let mut config = existing.cloned().unwrap_or(crate::cosim::CosimConfig {
        // A placeholder rather than a blank: `vw bench run` reports a missing
        // entity by name, which reads as an instruction.
        entity: format!("TODO_{name}_entity"),
        rust_components: Vec::new(),
        generics: Default::default(),
    });

    if let Some(dut) = dut {
        config.entity = dut.to_string();
    }
    // Added rather than replaced: the point of re-running is to grow the
    // list. Taking one back out is a matter of deleting it from the file,
    // which is where the list lives.
    for label in components {
        if !config.rust_components.iter().any(|have| have == label) {
            config.rust_components.push(label.clone());
        }
    }
    config.rust_components.sort();

    if !config.rust_components.is_empty() && config.entity.starts_with("TODO_")
    {
        return Err(VwError::Config {
            message: String::from(
                "--rust-component needs an entity: an instance is found \
                 inside a design, so there has to be one to look in. Pass \
                 --dut, or set `entity` in cosim.toml.",
            ),
        });
    }

    Ok(config)
}

/// The design this bench drives, and the instances it stands in for.
///
/// `None` when the config has no real entity yet — a bench created without
/// `--dut`, which is a valid thing to have and generates a driver that says
/// so.
struct Resolved {
    dut: Option<EntityInterface>,
    components: Vec<Instance>,
    types: DesignTypes,
}

fn resolve(
    workspace_dir: &Utf8Path,
    config: &crate::cosim::CosimConfig,
    vhdl_std: VhdlStandard,
) -> Result<Resolved> {
    if config.entity.starts_with("TODO_") {
        return Ok(Resolved {
            dut: None,
            components: Vec::new(),
            types: DesignTypes::default(),
        });
    }

    let dut = super::entity::load(workspace_dir, &config.entity, vhdl_std)?;
    // Only worth reading the design's type declarations when there is an
    // entity whose ports might use them.
    let types = super::entity::design_types(workspace_dir, vhdl_std)?;
    let components = config
        .rust_components
        .iter()
        .map(|label| {
            super::entity::find_instance(workspace_dir, &dut, label, vhdl_std)
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(Resolved {
        dut: Some(dut),
        components,
        types,
    })
}

/// Write `src/generated.rs`, which is derived from the design and nobody's to
/// edit.
fn ensure_generated(
    bench_dir: &Utf8Path,
    resolved: &Resolved,
) -> Result<Vec<Utf8PathBuf>> {
    let path = bench_dir.join("src").join("generated.rs");
    let contents = render_generated(
        resolved.dut.as_ref(),
        &resolved.components,
        &resolved.types,
    )?;
    Ok(if write_file(&path, &contents)? {
        vec![path]
    } else {
        Vec::new()
    })
}

/// Regenerate `src/generated.rs` for every cosim bench in the workspace.
///
/// Run before the benches build, for the same reason the mixed-signal
/// scaffolding is: the file is a function of the design, and a design that
/// has moved since the last run leaves it describing something that is no
/// longer there. Cheap when nothing changed — the write is content-aware, so
/// cargo does not see a new mtime.
pub fn ensure_all_generated(
    workspace_dir: &Utf8Path,
    vhdl_std: VhdlStandard,
) -> Result<()> {
    for (name, config) in
        crate::cosim::find_cosim_configs(&workspace_dir.join("bench"))?
    {
        let bench_dir = workspace_dir.join("bench").join(&name);
        let resolved = resolve(workspace_dir, &config, vhdl_std)?;
        ensure_generated(&bench_dir, &resolved)?;
    }
    Ok(())
}

fn next_steps(
    name: &str,
    config: &crate::cosim::CosimConfig,
    resolved: &Resolved,
    updating: bool,
    bench_dir: &Utf8Path,
) -> Vec<String> {
    let mut steps = Vec::new();

    // A bench made before the generated half was split out has all of it in
    // `lib.rs`, so the freshly written `generated.rs` sits there unread and
    // nothing said here has any effect. Better to say so than to report
    // success over a file nobody is compiling.
    let lib = bench_dir.join("src").join("lib.rs");
    // `mod generated;` exactly: a bench that includes anodizer's output says
    // `mod generated_structs`, which is a different file and would otherwise
    // pass for this one.
    let wired = std::fs::read_to_string(lib.as_std_path())
        .map(|text| text.contains("mod generated;"))
        .unwrap_or(true);
    if !wired {
        steps.push(format!(
            "`bench/{name}/src/lib.rs` predates the split and holds its own \
             copy of the generated code, so `src/generated.rs` is not being \
             compiled. Cut it down to `mod generated; pub use generated::*;` \
             and your `test()`, and the rest comes from there."
        ));
    }

    let Some(dut) = &resolved.dut else {
        steps.push(format!(
            "name the design entity in `bench/{name}/cosim.toml`, or re-run \
             with `--dut <entity>` to have the handles generated too"
        ));
        steps.push(format!("run it with `vw bench run {name}`"));
        return steps;
    };

    if !updating {
        steps.push(format!(
            "write the checks in `test()` in `bench/{name}/src/lib.rs` — \
             every one of {}'s ports already has a handle on `Tb`",
            dut.name,
        ));
    }

    for component in &resolved.components {
        steps.push(format!(
            "implement {} in `{}` — its outputs are yours to drive and its \
             inputs are what the design sends it",
            component.label,
            struct_name(&component.label),
        ));
    }

    let awkward: Vec<String> =
        plan_handles(dut, Side::Consumer, &resolved.types)
            .into_iter()
            .filter(|h| h.reach != Reach::Bits)
            .map(|h| h.signal)
            .collect();
    if !awkward.is_empty() {
        steps.push(format!(
            "check {}: an integer or composite signal has no bit string a \
             driver can read, so it is left out of `quiesce`",
            awkward.join(", "),
        ));
    }

    if dut.generics.iter().any(|g| g.default.is_none()) {
        steps.push(format!(
            "give the generics in `bench/{name}/cosim.toml` their values — \
             the design declares them without defaults, and with no wrapper \
             there is nowhere else to set them"
        ));
    }

    let _ = config;
    steps.push(format!("run it with `vw bench run {name}`"));
    steps
}

/// Write the files a cosim crate needs but does not own.
fn ensure_scaffold(bench_dir: &Utf8Path) -> Result<Vec<Utf8PathBuf>> {
    let mut written = Vec::new();
    for (path, contents) in [
        (bench_dir.join("build.rs"), BUILD_RS),
        (bench_dir.join(".gitignore"), GITIGNORE),
    ] {
        if write_file(&path, contents)? {
            written.push(path);
        }
    }
    Ok(written)
}

/// Put a cosim crate's `build.rs` back, if it is missing or is a stale copy
/// of one of ours.
///
/// Called for every cosim crate before a run. Two failures it exists to
/// prevent, both of which present as a link error with nothing in it about
/// `build.rs`: a crate created before this existed (or cleaned away by `git
/// clean -fdx`) has none at all, and one written by an older `vw` links
/// against the wrong thing.
///
/// A `build.rs` without the marker is somebody's — a bench that needs an
/// extra link flag, say — and is left exactly as it is. `.gitignore` is never
/// touched here either: a crate may well have one of its own, and repairing
/// a link error is no reason to overwrite it.
pub fn heal(bench_dir: &Utf8Path) -> Result<bool> {
    let path = bench_dir.join("build.rs");
    match std::fs::read_to_string(path.as_std_path()) {
        Ok(existing) if !existing.starts_with(BUILD_RS_MARKER) => Ok(false),
        _ => write_file(&path, BUILD_RS),
    }
}

/// Whether this directory holds a cosim testbench crate.
///
/// The `cdylib` is what makes it one: a crate under `bench/` that is not a
/// `cdylib` is a helper library (shared packet builders, register maps) which
/// is linked into the benches rather than loaded by the simulator, and giving
/// one a GPI-linking `build.rs` would break it. A directory with a
/// `mist.toml` is a mixed-signal bench, whose whole crate — `build.rs`
/// included — is generated from that file instead.
pub fn is_cosim_crate(dir: &Utf8Path) -> bool {
    if dir.join("mist.toml").exists() {
        return false;
    }
    let Ok(text) =
        std::fs::read_to_string(dir.join("Cargo.toml").as_std_path())
    else {
        return false;
    };
    let Ok(manifest) = text.parse::<toml::Value>() else {
        return false;
    };
    manifest.get("package").is_some()
        && manifest
            .get("lib")
            .and_then(|lib| lib.get("crate-type"))
            .and_then(toml::Value::as_array)
            .is_some_and(|kinds| {
                kinds.iter().any(|k| k.as_str() == Some("cdylib"))
            })
}

// ===========================================================================
// Working out what the driver can reach
// ===========================================================================

/// One handle on the generated `Tb`.
#[derive(Clone, Debug)]
struct Handle {
    /// The Rust field name: `bus_in_go`.
    field: String,
    /// How it reads in a message and a doc comment: `bus_in.go`.
    signal: String,
    /// The `get_child` chain from the top level down: `["bus_in", "go"]`.
    path: Vec<String>,
    /// The subtype it was declared with.
    subtype: String,
    /// Whether the driver owns it.
    driven: bool,
    reach: Reach,
}

/// Which side of an interface the driver is standing on.
///
/// For the design under test the driver is the outside world: it drives the
/// inputs and reads the outputs. For an instance the driver is *implementing*,
/// it is the component: it drives that instance's outputs and reads its
/// inputs. Getting this backwards produces a driver that fights the design
/// on every signal instead of feeding it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Side {
    /// Outside the entity, looking in.
    Consumer,
    /// Inside it, standing in for what is missing.
    Implementer,
}

impl Side {
    fn drives(self, port: &Interface) -> bool {
        match self {
            Side::Consumer => port.mode().is_driven(),
            Side::Implementer => !port.mode().is_driven(),
        }
    }
}

/// Work out every signal the driver should hold a handle to.
///
/// A record port contributes one handle per element rather than one for
/// itself: the aggregate is not a value, and reading it crashes the GPI
/// layer. Nested records are followed down, to a depth no real design reaches
/// but a self-referential one cannot exceed.
fn plan_handles(
    entity: &EntityInterface,
    side: Side,
    types: &DesignTypes,
) -> Vec<Handle> {
    let mut handles = Vec::new();
    for port in &entity.ports {
        expand(
            side.drives(port),
            &port.name,
            &port.subtype,
            vec![port.name.clone()],
            types,
            0,
            &mut handles,
        );
    }
    handles
}

/// A Rust type name for an instantiation label: `cips_wrapper_inst` becomes
/// `CipsWrapperInst`.
fn struct_name(label: &str) -> String {
    label
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    first.to_uppercase().collect::<String>()
                        + &chars.as_str().to_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}

fn expand(
    driven: bool,
    signal: &str,
    subtype: &str,
    path: Vec<String>,
    types: &DesignTypes,
    depth: usize,
    out: &mut Vec<Handle>,
) {
    // The depth cap is a guard against a source that declares a record
    // reachable from itself, which will not elaborate but should not hang
    // this either.
    if depth < 4 {
        if let Some(fields) = types.record(subtype) {
            for field in fields {
                let mut path = path.clone();
                path.push(field.name.clone());
                expand(
                    driven,
                    &format!("{signal}.{}", field.name),
                    &field.subtype,
                    path,
                    types,
                    depth + 1,
                    out,
                );
            }
            return;
        }
    }

    out.push(Handle {
        field: super::rust_field(&path.join("_")),
        signal: signal.to_string(),
        path,
        subtype: subtype.to_string(),
        driven,
        reach: types.reach(subtype),
    });
}

// ===========================================================================
// cosim.toml
// ===========================================================================

fn render_config(
    name: &str,
    config: &crate::cosim::CosimConfig,
    resolved: &Resolved,
) -> String {
    let mut out = String::from(
        "# Rust cosim testbench.\n\
         #\n\
         # The entity named here is the top level: nvc elaborates it as it \
         stands\n\
         # and the crate beside this file is the only thing driving it. There \
         is no\n\
         # VHDL harness.\n\
         #\n\
         # This file is what `src/generated.rs` is generated from, and \
         `vw cosim init`\n\
         # reads it back — so a bench can be added to a piece at a time \
         without the\n\
         # command line having to repeat itself.\n\
         \n",
    );

    if resolved.dut.is_none() {
        out.push_str("# TODO: the design entity this bench drives.\n");
    }
    out.push_str(&format!("entity = \"{}\"\n", config.entity));

    if !config.rust_components.is_empty() {
        out.push_str(
            "\n# Instances the driver implements rather than observes — a \
             vivado IP\n\
             # wrapper with no simulation model, say. Each gets a struct of \
             its own in\n\
             # src/generated.rs, with the directions the other way round: \
             what the\n\
             # instance declares `out` is driven from Rust. Add one with\n\
             # `vw cosim init <name> --rust-component <label>`; remove one \
             by deleting\n\
             # it here.\n\
             rust-components = [\n",
        );
        for label in &config.rust_components {
            out.push_str(&format!("    \"{label}\",\n"));
        }
        out.push_str("]\n");
    }

    let Some(dut) = &resolved.dut else {
        return out;
    };

    let awkward: Vec<Handle> =
        plan_handles(dut, Side::Consumer, &resolved.types)
            .into_iter()
            .filter(|h| h.reach != Reach::Bits)
            .collect();
    if !awkward.is_empty() {
        out.push_str(
            "\n# Signals with no bit string a driver can read. An integer \
             port comes\n\
             # back empty, and an array of composites has no single value \
             that means\n\
             # anything. They have handles in src/generated.rs but are left \
             out of\n\
             # `quiesce`:\n\
             #\n",
        );
        for handle in &awkward {
            out.push_str(&format!(
                "#   {} : {}\n",
                handle.signal, handle.subtype,
            ));
        }
    }

    if dut.generics.is_empty() {
        return out;
    }

    out.push_str(
        "\n# Generic overrides, applied at elaboration. With no wrapper there \
         is\n\
         # nowhere else to set them, so a generic the design declares without \
         a\n\
         # default has to have a value here or elaboration fails.\n\
         [generics]\n",
    );
    let width = dut.generics.iter().map(|g| g.name.len()).max().unwrap_or(0);
    for generic in &dut.generics {
        // Whatever is already in the file wins: it was put there on purpose,
        // and regeneration is not the place to take it back out.
        if let Some(set) = config.generics.get(&generic.name) {
            out.push_str(&format!("{:width$} = \"{set}\"\n", generic.name,));
            continue;
        }
        match &generic.default {
            // Commented out: the design's own default already applies, and an
            // entry here would be a second place to keep it up to date.
            Some(default) => out.push_str(&format!(
                "# {:width$} = \"{default}\"   # the design's default\n",
                generic.name,
            )),
            None => out.push_str(&format!(
                "{:width$} = \"{}\"   # TODO: no default in {}\n",
                generic.name,
                super::placeholder(generic, &resolved.types)
                    .unwrap_or_else(|| "1".to_string()),
                dut.name,
            )),
        }
    }
    let _ = name;
    out
}

fn render_manifest(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

# The simulator dlopens this, so it has to be a C-ABI shared library rather
# than an rlib. Without this the crate builds and the bench then fails with
# nothing to load.
[lib]
crate-type = ["cdylib"]

[dependencies]
rust-cosim.workspace = true
futures.workspace = true
log.workspace = true
env_logger.workspace = true
"#
    )
}

// ===========================================================================
// src/lib.rs
// ===========================================================================

/// A `///` comment, one attribute per line.
///
/// `quote!` drops `//` comments — the lexer discards them before the macro
/// sees them — so everything a generated file has to say has to be said in
/// doc attributes, which `prettyplease` renders back as `///`.
fn doc(text: &str) -> TokenStream {
    let lines = text.lines().map(|line| {
        let line = if line.is_empty() {
            String::new()
        } else {
            format!(" {line}")
        };
        quote!(#[doc = #line])
    });
    quote!(#(#lines)*)
}

/// The same, as `//!`.
fn module_doc(text: &str) -> TokenStream {
    let lines = text.lines().map(|line| {
        let line = if line.is_empty() {
            String::new()
        } else {
            format!(" {line}")
        };
        quote!(#![doc = #line])
    });
    quote!(#(#lines)*)
}

/// `src/lib.rs` — written once, then the developer's.
///
/// Deliberately thin. Everything that follows from the design is next door in
/// `generated.rs`, so adding a second Rust component later rewrites that and
/// leaves whatever has been written here untouched.
fn render_lib(config: &crate::cosim::CosimConfig) -> String {
    let entity = &config.entity;
    format!(
        r#"//! Cosim testbench for `{entity}`.
//!
//! This file is yours. `src/generated.rs` holds the signal handles and the
//! entry point, and is rewritten whenever the design changes or another
//! `--rust-component` is added — so nothing written here is at risk from
//! either.

mod generated;

pub use generated::*;

use rust_cosim::TestError;

/// What this bench checks.
///
/// Called once, after the design has been quiesced.
///
/// TODO: this is the part that is yours. Drive a signal with `tb.drive()`,
/// read one with `tb.read_bit()` or `tb.read_int()`, and step time with
/// `tick()`:
///
/// ```ignore
/// // A period in femtoseconds: 1e15 / 250e6 is 250 MHz. See `tick`.
/// const PERIOD: u64 = 4_000_000;
///
/// for _ in 0..8 {{
///     tick(&tb.some_clock, PERIOD).await;
/// }}
/// ```
///
/// Nothing generates a clock for you — which of a design's signals this bench
/// should drive, at what rate, and whether two of them run together is the
/// test's business. Two clock domains means two `tick` loops under a
/// `futures::join!`, not two calls in a row.
///
/// Returning `Err` is what fails the bench. A panic is reported as a crash,
/// and an `assert!` that fires is a panic.
pub async fn test(tb: &Tb) -> Result<(), TestError> {{
    let _ = tb;
    Ok(())
}}
"#
    )
}

fn render_generated(
    dut: Option<&EntityInterface>,
    components: &[Instance],
    types: &DesignTypes,
) -> Result<String> {
    let entity = dut.map(|d| d.name.as_str()).unwrap_or("the design");

    let header = module_doc(&format!(
        "Generated from `{entity}` and `cosim.toml`. Do not edit — \
         `vw cosim init`\n\
         and `vw bench run` both rewrite this file. The test lives in \
         `lib.rs`.\n\
         \n\
         \n\
         nvc elaborates `{entity}` as the top level and loads this library \
         beside\n\
         it. There is no VHDL harness: everything the design sees is driven \
         from\n\
         here, its clock included, so simulation time only advances when this\n\
         asks it to.\n\
         \n\
         Signals are looked up by name, so a port renamed in the design has \
         to be\n\
         renamed here too — the mismatch is a run-time `TestError`, not a \
         build\n\
         failure."
    ));

    let body = match dut {
        Some(dut) => with_dut(dut, components, types),
        None => without_dut(),
    };

    let tokens = quote! {
        #header
        #![allow(dead_code)]

        use rust_cosim::handles::{SetAction, SimHandle};
        use rust_cosim::triggers::{ReadOnly, Timer};
        use rust_cosim::TestError;
        use std::future::Future;
        use std::pin::Pin;

        #body
    };

    let file =
        syn::parse2::<syn::File>(tokens).map_err(|e| VwError::CodeGen {
            message: format!("generated driver does not parse: {e}"),
        })?;
    Ok(prettyplease::unparse(&file))
}

/// Toggling a signal, which is how a bench makes time pass.
///
/// One free function rather than a method, so it works on any handle — a port
/// of the design, or one belonging to an instance the driver implements —
/// without going through whatever struct happens to hold it.
///
/// Generated rather than left to the developer for one reason: the unit.
/// `Timer` counts nvc's time step, which is a femtosecond, and a bench that
/// assumes picoseconds runs perfectly happily at a thousand times the wrong
/// speed without ever saying so.
fn tick_fn() -> TokenStream {
    let docs = doc("Drive one period of `clk`.\n\
         \n\
         `period_fs` is femtoseconds, which is nvc's time step — 250 MHz is\n\
         `1e15 / 250e6`, or 4_000_000. Assuming picoseconds gives a bench \
         that\n\
         runs a thousand times too fast and never complains about it.\n\
         \n\
         Nothing else drives the signal, so time advances when this is called\n\
         and not otherwise. Two clocks running together is two of these under\n\
         a `futures::join!`; two calls in a row is one clock and then the\n\
         other.");
    quote! {
        #docs
        pub async fn tick(clk: &SimHandle, period_fs: u64) {
            let half = period_fs / 2;
            clk.set_value_binstr("1", SetAction::NoDelay);
            Timer::new(half).await;
            clk.set_value_binstr("0", SetAction::NoDelay);
            Timer::new(half).await;
        }
    }
}

/// The part of the driver that exists whether or not there is a design to
/// drive: getting the simulator moving, and the entry point.
fn prime_fn() -> TokenStream {
    let docs = doc(
        "Give the simulator something to do before anything else is awaited.\n\
         \n\
         With no VHDL harness, nothing in the design schedules an event of \
         its\n\
         own. Unless a timed callback is registered first, the simulator \
         finds no\n\
         work at time zero and ends the run before the test has started.",
    );
    quote! {
        #docs
        async fn prime() {
            Timer::new(1).await;
        }
    }
}

fn without_dut() -> TokenStream {
    let prime = prime_fn();
    let tick = tick_fn();
    let docs = doc("The design under test, once `cosim.toml` names one.\n\
         \n\
         TODO: it does not yet. Set `entity`, or re-run `vw cosim init` with\n\
         `--dut <entity>`, and this becomes a handle per port of it.");
    quote! {
        #docs
        pub struct Tb {
            pub dut: SimHandle,
        }

        impl Tb {
            fn new(dut: &SimHandle) -> Result<Self, TestError> {
                Ok(Self { dut: *dut })
            }
        }

        #prime
        #tick

        #[no_mangle]
        pub fn testbench_main(
            dut: SimHandle,
        ) -> Pin<Box<dyn Future<Output = Result<(), TestError>>>> {
            env_logger::Builder::from_env(
                env_logger::Env::default().default_filter_or("info"),
            )
            .init();

            Box::pin(async move {
                let tb = Tb::new(&dut)?;
                prime().await;
                crate::test(&tb).await?;
                Ok(())
            })
        }
    }
}

fn with_dut(
    dut: &EntityInterface,
    components: &[Instance],
    types: &DesignTypes,
) -> TokenStream {
    let handles = plan_handles(dut, Side::Consumer, types);
    let parts: Vec<ComponentPart> = components
        .iter()
        .map(|component| ComponentPart::new(component, types))
        .collect();
    let struct_docs = doc(&format!("Handles to `{}`'s signals.", dut.name));
    let fields = handles.iter().map(|handle| {
        let field = format_ident!("{}", handle.field);
        let note = match handle.reach {
            Reach::Bits => String::new(),
            Reach::Integer => {
                ", reads back empty — integers have no bit string".to_string()
            }
            // Only reachable past the recursion cap; a record within reach
            // was expanded into its elements above.
            Reach::Record | Reach::Unknown => {
                ", not a bit string this can size".to_string()
            }
        };
        let docs = doc(&format!(
            "`{}` — {} ({}{note})",
            handle.signal,
            if handle.driven {
                "driven from here"
            } else {
                "driven by the design"
            },
            handle.subtype,
        ));
        quote! { #docs pub #field: SimHandle }
    });

    let lookups = handles.iter().map(|handle| {
        let field = format_ident!("{}", handle.field);
        // A record element is reached through its port, one `get_child` per
        // step: the aggregate handle exists but is not a value.
        let mut expr = quote! { dut };
        for step in &handle.path {
            let step = Literal::string(step);
            expr = quote! { #expr.get_child(#step)? };
        }
        quote! { #field: #expr }
    });

    let component_fields = parts.iter().map(ComponentPart::field);
    let component_lookups = parts.iter().map(ComponentPart::lookup);
    let component_quiesce = parts.iter().map(ComponentPart::quiesce_call);
    let component_structs = parts.iter().map(ComponentPart::definition);

    let new_docs = doc("Look every signal up by name.\n\
         \n\
         A record element is reached through its port — `bus.field`, not\n\
         `bus_field` — because that is where the simulator keeps it.");
    let quiesce = quiesce_fn(&handles);
    let helpers = helper_fns();
    let prime = prime_fn();
    let tick = tick_fn();

    let starting = Literal::string(&format!("{} starting", dut.name));
    let complete = Literal::string(&format!("{} complete", dut.name));
    quote! {
        #struct_docs
        pub struct Tb {
            #(#fields,)*
            #(#component_fields,)*
        }

        impl Tb {
            #new_docs
            fn new(dut: &SimHandle) -> Result<Self, TestError> {
                Ok(Self {
                    #(#lookups,)*
                    #(#component_lookups,)*
                })
            }

            #quiesce
            #helpers
        }

        #(#component_structs)*

        #prime
        #tick

        #[no_mangle]
        pub fn testbench_main(
            dut: SimHandle,
        ) -> Pin<Box<dyn Future<Output = Result<(), TestError>>>> {
            env_logger::Builder::from_env(
                env_logger::Env::default().default_filter_or("info"),
            )
            .init();

            Box::pin(async move {
                log::info!(#starting);
                let tb = Tb::new(&dut)?;

                prime().await;
                tb.quiesce();
                #(#component_quiesce)*

                // The test itself lives in `lib.rs`, which this file is
                // regenerated around rather than over.
                crate::test(&tb).await?;

                log::info!(#complete);
                Ok(())
            })
        }
    }
}

/// One instance the driver stands in for, ready to be written out.
///
/// Kept apart from the design's own signals rather than folded in with them,
/// because they are not the same thing: `tb.brq_request_tvalid` would read as
/// something the design under test exposes, when it is something this driver
/// is pretending to be.
struct ComponentPart {
    /// The instantiation label, as `get_child` will ask for it.
    label: String,
    /// The Rust field on `Tb`.
    field: proc_macro2::Ident,
    /// The struct holding this instance's signals.
    name: proc_macro2::Ident,
    /// What it is standing in for, for the doc comment.
    entity: String,
    handles: Vec<Handle>,
}

impl ComponentPart {
    fn new(component: &Instance, types: &DesignTypes) -> Self {
        Self {
            label: component.label.clone(),
            field: format_ident!("{}", super::rust_field(&component.label)),
            name: format_ident!("{}", struct_name(&component.label)),
            entity: component.interface.name.clone(),
            handles: plan_handles(
                &component.interface,
                Side::Implementer,
                types,
            ),
        }
    }

    fn field(&self) -> TokenStream {
        let (field, name, label) = (&self.field, &self.name, &self.label);
        let docs = doc(&format!("The `{label}` instance, implemented here."));
        quote! { #docs pub #field: #name }
    }

    fn lookup(&self) -> TokenStream {
        let (field, name) = (&self.field, &self.name);
        let label = Literal::string(&self.label);
        quote! { #field: #name::new(&dut.get_child(#label)?)? }
    }

    fn quiesce_call(&self) -> TokenStream {
        let field = &self.field;
        quote! { tb.#field.quiesce(); }
    }

    fn definition(&self) -> TokenStream {
        let name = &self.name;
        let docs = doc(&format!(
            "The `{}` instance of `{}`.\n\
             \n\
             This driver is the component, not its consumer, so the \
             directions\n\
             read the other way round from `Tb`: what the entity declares \
             `out` is\n\
             driven from here, and what it declares `in` is what the design \
             is\n\
             sending. Reached through the instance rather than the top \
             level, so\n\
             none of it has to be a port of anything.",
            self.label, self.entity,
        ));

        let fields = self.handles.iter().map(|handle| {
            let field = format_ident!("{}", handle.field);
            let note = match handle.reach {
                Reach::Bits => String::new(),
                Reach::Integer => {
                    ", reads back empty — integers have no bit string"
                        .to_string()
                }
                Reach::Record | Reach::Unknown => {
                    ", not a bit string this can size".to_string()
                }
            };
            let docs = doc(&format!(
                "`{}` — {} ({}{note})",
                handle.signal,
                if handle.driven {
                    "driven from here"
                } else {
                    "sent by the design"
                },
                handle.subtype,
            ));
            quote! { #docs pub #field: SimHandle }
        });

        let lookups = self.handles.iter().map(|handle| {
            let field = format_ident!("{}", handle.field);
            let mut expr = quote! { instance };
            for step in &handle.path {
                let step = Literal::string(step);
                expr = quote! { #expr.get_child(#step)? };
            }
            quote! { #field: #expr }
        });

        let quiesce = quiesce_fn(&self.handles);
        let helpers = helper_fns();
        quote! {
            #docs
            pub struct #name {
                #(#fields,)*
            }

            impl #name {
                fn new(instance: &SimHandle) -> Result<Self, TestError> {
                    Ok(Self { #(#lookups,)* })
                }

                #quiesce
                #helpers
            }
        }
    }
}

fn quiesce_fn(handles: &[Handle]) -> TokenStream {
    let writes = handles.iter().filter(|h| h.driven).filter_map(|handle| {
        let field = format_ident!("{}", handle.field);
        match handle.reach {
            Reach::Bits => Some(quote! { self.drive(&self.#field, 0); }),
            Reach::Integer => Some(quote! {
                self.#field.set_value_int(0, SetAction::NoDelay);
            }),
            // Nothing sensible to write: see the note on the handle.
            Reach::Record | Reach::Unknown => None,
        }
    });
    let docs = doc("Put every input at a defined value.\n\
         \n\
         An input left at 'U' propagates into the design and buries the run \
         in\n\
         numeric_std metavalue warnings long before any check fails.");
    quote! {
        #docs
        pub fn quiesce(&self) {
            #(#writes)*
        }
    }
}

fn helper_fns() -> TokenStream {
    let drive_docs = doc(
        "Drive a signal with an unsigned value, whatever its width.\n\
         \n\
         The bit string is sized from the signal itself, so this works the \
         same\n\
         on a `std_logic`, a `std_logic_vector`, a subtype of either, and a \
         port\n\
         whose width comes from a generic — none of which have to be known \
         here.",
    );
    let bit_docs = doc("Read a logic signal as a bit.\n\
         \n\
         Anything that is not '1' — 'U' and 'X' included — reads as false, \
         which\n\
         is what a check wants.");
    let int_docs = doc("Read a logic vector as an unsigned integer.\n\
         \n\
         Fails rather than guessing if any bit is a metavalue, since a\n\
         half-undefined vector is not a number and silently reading it as one\n\
         turns a real bug into a passing check.");
    quote! {
        #drive_docs
        pub fn drive(&self, signal: &SimHandle, value: u64) {
            let width = signal.get_range().max(1);
            let bits = format!("{value:0width$b}");
            signal.set_value_binstr(
                &bits[bits.len() - width..],
                SetAction::NoDelay,
            );
        }

        #bit_docs
        pub async fn read_bit(&self, signal: &SimHandle) -> bool {
            ReadOnly::new().await;
            signal.get_value_binstr().as_deref() == Some("1")
        }

        #int_docs
        pub async fn read_int(
            &self,
            signal: &SimHandle,
        ) -> Result<u64, TestError> {
            ReadOnly::new().await;
            let bits = signal.get_value_binstr().unwrap_or_default();
            u64::from_str_radix(&bits, 2).map_err(|_| {
                TestError::ValueError(format!("not a number: '{bits}'"))
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bench_init::entity::{PortMode, RecordField};

    fn port(name: &str, mode: PortMode, subtype: &str) -> Interface {
        Interface {
            name: name.to_string(),
            mode: Some(mode),
            subtype: subtype.to_string(),
            default: None,
        }
    }

    fn dut() -> EntityInterface {
        EntityInterface {
            name: "flit_fifo".to_string(),
            file: std::path::PathBuf::from("hdl/flit_fifo.vhd"),
            context: Vec::new(),
            generics: vec![
                Interface {
                    name: "DATA_W".to_string(),
                    mode: None,
                    subtype: "positive".to_string(),
                    default: Some("32".to_string()),
                },
                Interface {
                    name: "FAST_READ".to_string(),
                    mode: None,
                    subtype: "boolean".to_string(),
                    default: None,
                },
            ],
            ports: vec![
                port("clk", PortMode::In, "std_logic"),
                port("rstn", PortMode::In, "std_logic"),
                port(
                    "write_data",
                    PortMode::In,
                    "std_logic_vector(DATA_W - 1 downto 0)",
                ),
                // A subtype: nothing about its width is knowable from here.
                port("tap", PortMode::In, "Nibble"),
                // A record: one handle per element, not one for the whole.
                port("bus_in", PortMode::In, "lrq"),
                port("empty", PortMode::Out, "std_logic"),
                // An integer: drivable, but it does not read back.
                port("level", PortMode::Out, "natural"),
            ],
        }
    }

    fn types() -> DesignTypes {
        let mut types = DesignTypes::default();
        types
            .subtypes
            .insert("nibble".into(), "std_logic_vector(3 downto 0)".into());
        types.records.insert(
            "lrq".into(),
            vec![
                RecordField {
                    name: "valid".into(),
                    subtype: "std_logic".into(),
                },
                RecordField {
                    name: "data".into(),
                    subtype: "Nibble".into(),
                },
            ],
        );
        types
    }

    fn driver() -> String {
        render_generated(Some(&dut()), &[], &types()).unwrap()
    }

    /// The generated file has to be valid Rust. It is built as a token tree
    /// and parsed before it is written, so this can only fail loudly.
    #[test]
    fn the_driver_is_syntactically_valid_rust() {
        syn::parse_file(&driver()).expect("generated driver parses");
    }

    /// `quote!` drops `//` comments — the lexer discards them before the
    /// macro sees them — so everything the file has to explain has to survive
    /// as a doc attribute.
    #[test]
    fn the_explanations_survive_code_generation() {
        let text = driver();
        assert!(
            text.contains("//! Generated from `flit_fifo` and `cosim.toml`.")
        );
        assert!(text.contains("/// Drive one period of `clk`."));
        // The part that is the developer's says so, in the file that is
        // theirs rather than the one that gets rewritten.
        let lib = render_lib(&config("flit_fifo", &[]));
        assert!(lib.contains("TODO: this is the part that is yours."));
        assert!(lib.contains("pub async fn test(tb: &Tb)"));
        assert!(!text.contains("TODO: this is the part that is yours."));
    }

    /// A record port is reached one element at a time: the aggregate handle
    /// exists but is not a value, and reading it crashes the GPI layer.
    #[test]
    fn record_ports_become_one_handle_per_element() {
        let text = driver();

        assert!(text.contains("pub bus_in_valid: SimHandle"));
        assert!(text.contains("pub bus_in_data: SimHandle"));
        assert!(
            text.contains(
                r#"bus_in_valid: dut.get_child("bus_in")?.get_child("valid")?"#
            ),
            "the element is reached through its port",
        );
        // And never the aggregate on its own.
        assert!(!text.contains("pub bus_in: SimHandle"));
    }

    /// A subtype needs no special handling as long as nothing assumes a
    /// width: the signal knows its own.
    #[test]
    fn subtype_ports_are_driven_by_their_own_width() {
        let text = driver();
        assert!(text.contains("pub tap: SimHandle"));
        assert!(text.contains("self.drive(&self.tap, 0);"));
        assert!(text.contains("let width = signal.get_range().max(1);"));
    }

    /// The generated `tick` halves the period it is given, so a caller
    /// thinks in the unit it named — a period, not a half-period.
    #[test]
    fn tick_takes_a_period_and_halves_it() {
        let text = driver();
        assert!(text.contains("let half = period_fs / 2;"));
        assert!(text.contains("Timer::new(half).await;"));
    }

    /// The first thing awaited must be a timed callback: without one the
    /// simulator finds nothing to do at time zero and ends before the test.
    #[test]
    fn the_simulator_is_primed_before_anything_else() {
        let text = driver();
        let prime = text.find("prime().await;").expect("primed");
        let quiesce = text.find("tb.quiesce();").expect("quiesced");
        let test = text.find("test(&tb).await?;").expect("test runs");
        assert!(prime < quiesce && quiesce < test);
        assert!(text.contains("Timer::new(1).await;"));
    }

    /// Everything the driver owns starts at a defined value, nothing it does
    /// not own is touched, and nothing it cannot size is guessed at.
    #[test]
    fn the_driver_quiesces_only_what_it_can() {
        let text = driver();
        assert!(text.contains("self.drive(&self.write_data, 0);"));
        assert!(text.contains("self.drive(&self.bus_in_valid, 0);"));
        // An output is the design's to drive.
        assert!(!text.contains("self.drive(&self.empty"));
        // ...and `level` is an output too, so it is not driven either.
        assert!(!text.contains("self.level.set_value_int"));
    }

    /// Time passes by toggling a signal, and the unit is the thing worth
    /// generating: `Timer` counts femtoseconds, and a bench that assumes
    /// picoseconds runs a thousand times too fast without ever saying so.
    #[test]
    fn ticking_is_offered_but_never_decided() {
        let text = driver();

        assert!(
            text.contains("pub async fn tick(clk: &SimHandle, period_fs: u64)")
        );
        assert!(text.contains("`period_fs` is femtoseconds"));

        // Nothing picks a clock. A design has as many as it has, with names
        // that say nothing about which is which, so the test says.
        assert!(!text.contains("async fn tick_"));
    }

    /// A generic with no default has to be set somewhere, and with no wrapper
    /// `cosim.toml` is the only somewhere there is.
    #[test]
    fn generics_without_defaults_are_surfaced() {
        let text = render_config(
            "fifo",
            &config("flit_fifo", &[]),
            &resolved(Some(dut()), Vec::new()),
        );
        let parsed: crate::cosim::CosimConfig =
            toml::from_str(&text).expect("valid toml");

        assert_eq!(parsed.entity, "flit_fifo");
        assert!(
            parsed.generics.contains_key("FAST_READ"),
            "a generic with no default must be set or elaboration fails",
        );
        assert!(
            !parsed.generics.contains_key("DATA_W"),
            "one with a default is left to the design, not restated here",
        );
    }

    /// The config says which signals the driver could not size, or their
    /// absence from `quiesce` looks like an oversight.
    #[test]
    fn the_config_names_the_signals_it_could_not_size() {
        let text = render_config(
            "fifo",
            &config("flit_fifo", &[]),
            &resolved(Some(dut()), Vec::new()),
        );
        assert!(text.contains("level : natural"));
        // ...and does not complain about the ones that are fine.
        assert!(!text.contains("tap : Nibble"));
        assert!(!text.contains("write_data :"));
    }

    /// Without an entity there is still a parseable config and a driver that
    /// builds.
    #[test]
    fn a_bench_with_no_dut_still_stands_on_its_own() {
        let text = render_config(
            "fifo",
            &config("TODO_fifo_entity", &[]),
            &resolved(None, Vec::new()),
        );
        let parsed: crate::cosim::CosimConfig =
            toml::from_str(&text).expect("valid toml");
        assert!(parsed.entity.starts_with("TODO_"));

        let driver =
            render_generated(None, &[], &DesignTypes::default()).unwrap();
        syn::parse_file(&driver).expect("generated driver parses");
        assert!(driver.contains("prime().await;"));
    }

    fn wrapper() -> Instance {
        Instance {
            label: "cips_wrapper_inst".to_string(),
            interface: EntityInterface {
                name: "cips_wrapper".to_string(),
                file: std::path::PathBuf::from("target/ip/cips/wrapper.vhd"),
                context: Vec::new(),
                generics: Vec::new(),
                ports: vec![
                    // The design sends these to the IP.
                    port(
                        "lrq_request_tdata",
                        PortMode::In,
                        "std_logic_vector(1023 downto 0)",
                    ),
                    port("lrq_request_tvalid", PortMode::In, "std_logic"),
                    // The IP sends these back — the driver's job.
                    port(
                        "brq_request_tdata",
                        PortMode::Out,
                        "std_logic_vector(1023 downto 0)",
                    ),
                    port("brq_request_tvalid", PortMode::Out, "std_logic"),
                ],
            },
        }
    }

    fn config(entity: &str, components: &[&str]) -> crate::cosim::CosimConfig {
        crate::cosim::CosimConfig {
            entity: entity.to_string(),
            rust_components: components.iter().map(|s| s.to_string()).collect(),
            generics: Default::default(),
        }
    }

    fn resolved(
        dut: Option<EntityInterface>,
        components: Vec<Instance>,
    ) -> Resolved {
        Resolved {
            dut,
            components,
            types: types(),
        }
    }

    fn with_component() -> String {
        render_generated(
            Some(&dut()),
            std::slice::from_ref(&wrapper()),
            &types(),
        )
        .unwrap()
    }

    /// An instantiation label becomes a Rust type name.
    #[test]
    fn a_label_becomes_a_struct_name() {
        assert_eq!(struct_name("cips_wrapper_inst"), "CipsWrapperInst");
        assert_eq!(struct_name("dma_inst"), "DmaInst");
        assert_eq!(struct_name("fifo"), "Fifo");
    }

    /// The driver *is* the component, so the directions read the other way
    /// round from the design under test: what the entity declares `out` is
    /// driven from here. Backwards, the driver fights the design on every
    /// signal instead of feeding it.
    #[test]
    fn a_components_directions_are_inverted() {
        let text = with_component();

        assert!(text
            .contains("`brq_request_tvalid` — driven from here (std_logic)"));
        assert!(text
            .contains("`lrq_request_tvalid` — sent by the design (std_logic)"));

        // ...and quiescing drives what the driver owns, which is the outputs.
        let component =
            &text[text.find("impl CipsWrapperInst").expect("component impl")..];
        assert!(component.contains("self.drive(&self.brq_request_tdata, 0);"));
        assert!(!component.contains("self.drive(&self.lrq_request_tdata, 0);"));
    }

    /// The signals live in their own struct rather than among the design's,
    /// and are reached through the instance rather than the top level — which
    /// is what lets them be signals that are not ports of anything.
    #[test]
    fn a_component_gets_its_own_struct_reached_through_the_instance() {
        let text = with_component();

        assert!(text.contains("pub struct CipsWrapperInst"));
        assert!(text.contains("pub cips_wrapper_inst: CipsWrapperInst"));
        assert!(
            text.contains("CipsWrapperInst::new(")
                && text.contains(r#"dut.get_child("cips_wrapper_inst")?"#),
            "the struct is built from the instance's own handle",
        );
        assert!(text.contains(
            r#"brq_request_tdata: instance.get_child("brq_request_tdata")?"#
        ));

        // The design's own handles stay on `Tb`, not folded in with them.
        let tb = &text[text.find("pub struct Tb").expect("Tb")
            ..text.find("impl Tb").expect("impl Tb")];
        assert!(tb.contains("pub write_data: SimHandle"));
        assert!(!tb.contains("brq_request_tdata"));
    }

    /// A component is quiesced alongside the design, or its outputs reach the
    /// design as 'U'.
    #[test]
    fn a_component_is_quiesced_at_startup() {
        let text = with_component();
        let quiesce = text.find("tb.quiesce();").expect("tb quiesce");
        let component = text
            .find("tb.cips_wrapper_inst.quiesce();")
            .expect("component");
        let test = text.find("test(&tb).await?;").expect("test");
        assert!(quiesce < component && component < test);
    }

    /// The crate has to be a cdylib or there is nothing for the simulator to
    /// load, and it has to reach rust-cosim through the bench workspace.
    #[test]
    fn the_manifest_builds_something_the_simulator_can_load() {
        let text = render_manifest("fifo");
        assert!(text.contains(r#"crate-type = ["cdylib"]"#));
        assert!(text.contains("rust-cosim.workspace = true"));
    }

    fn crate_at(kind: &str) -> (tempfile::TempDir, Utf8PathBuf) {
        let guard = tempfile::tempdir().unwrap();
        let dir =
            Utf8PathBuf::from_path_buf(guard.path().to_path_buf()).unwrap();
        std::fs::write(dir.join("Cargo.toml"), kind).unwrap();
        (guard, dir)
    }

    /// A `cdylib` under `bench/` is a testbench. A plain library is shared
    /// helper code the benches link against, and giving one a GPI-linking
    /// `build.rs` would break it.
    #[test]
    fn only_cdylib_crates_count_as_cosim_benches() {
        let (_g, bench) = crate_at(
            "[package]\nname = \"b\"\n[lib]\ncrate-type = [\"cdylib\"]\n",
        );
        assert!(is_cosim_crate(&bench));

        let (_g, helper) = crate_at("[package]\nname = \"helpers\"\n");
        assert!(!is_cosim_crate(&helper));

        let (_g, manifest_only) = crate_at("[workspace]\nmembers = []\n");
        assert!(!is_cosim_crate(&manifest_only));

        // A mixed-signal bench's whole crate is generated from its mist.toml,
        // build.rs included, so it is not this code's business.
        let (_g, mixed) = crate_at(
            "[package]\nname = \"m\"\n[lib]\ncrate-type = [\"cdylib\"]\n",
        );
        std::fs::write(mixed.join("mist.toml"), "").unwrap();
        assert!(!is_cosim_crate(&mixed));
    }

    /// The failure this exists for: a clone or a `git clean -fdx` leaves a
    /// cosim crate with no `build.rs`, and the bench then fails at link time
    /// with an error that says nothing about it.
    #[test]
    fn a_missing_build_script_is_put_back() {
        let (_g, dir) = crate_at("[package]\nname = \"b\"\n");

        assert!(heal(&dir).unwrap());
        assert!(dir.join("build.rs").exists());
        // Already right — nothing rewritten, so cargo's incremental build
        // stays hot.
        assert!(!heal(&dir).unwrap());
    }

    /// A `build.rs` somebody wrote — a bench needing an extra link flag — is
    /// never replaced. Repairing a link error is no reason to throw away work.
    #[test]
    fn a_hand_written_build_script_is_left_alone() {
        let (_g, dir) = crate_at("[package]\nname = \"b\"\n");
        std::fs::write(dir.join("build.rs"), "fn main() { /* mine */ }")
            .unwrap();

        assert!(!heal(&dir).unwrap());
        assert!(std::fs::read_to_string(dir.join("build.rs"))
            .unwrap()
            .contains("mine"));
    }

    /// One written by an older vw is ours to bring up to date.
    #[test]
    fn a_stale_generated_build_script_is_replaced() {
        let (_g, dir) = crate_at("[package]\nname = \"b\"\n");
        std::fs::write(
            dir.join("build.rs"),
            "// Auto-generated by vw — from some earlier version\n",
        )
        .unwrap();

        assert!(heal(&dir).unwrap());
        assert_eq!(
            std::fs::read_to_string(dir.join("build.rs")).unwrap(),
            BUILD_RS,
        );
    }
}
