// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! `vw cosim init` — a Rust cosim testbench.
//!
//! The design entity is the top level. nvc elaborates it as it stands and
//! loads a `cdylib` beside it; that library reaches the entity's ports over
//! VHPI and drives them, clock included. There is no VHDL harness — a
//! passthrough wrapper would only be a second copy of the port list to keep
//! in step with the design.
//!
//! What that leaves is a crate, a `build.rs` that finds the GPI libraries, a
//! `cosim.toml` saying which entity, and a registration in the bench cargo
//! workspace. All of it is written here.
//!
//! ## Reaching the ports
//!
//! A record port is not a value in itself — reading the aggregate handle is
//! a category error, and the GPI layer crashes rather than saying so — but
//! its elements are. So a record port becomes one handle per element,
//! `bus_in.go` reached as `dut.get_child("bus_in")?.get_child("go")?`, and
//! nested records are followed down.
//!
//! Subtypes need no special handling at all, as long as nothing is assumed
//! about width at generation time: a signal knows its own, so everything the
//! driver writes is sized from `get_range()` rather than from the type it was
//! declared with. That also makes a port whose width comes from a generic
//! work without the generic being mentioned.
//!
//! What is left over is genuinely awkward and is reported rather than
//! guessed at: an `integer`/`natural` port reads back as an empty bit string,
//! and an array-of-composite has no single bit string that means anything.
//! Both get a handle, and a note saying so.

use camino::{Utf8Path, Utf8PathBuf};
use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use super::entity::{DesignTypes, EntityInterface, Interface, Reach};
use super::{write_file, write_new_file, Created};
use crate::{Result, VhdlStandard, VwError};

/// Default clock for a bench that did not say: 100 MHz.
const DEFAULT_CLOCK_HZ: f64 = 100e6;

/// The link flags every cosim crate needs, and the only thing in one.
///
/// Regenerated rather than checked in: it is identical in every bench, it is
/// derived from where `rust-cosim` put its GPI libraries, and a bench whose
/// copy has gone missing or gone stale fails at link time with an error that
/// says nothing about any of that. `vw bench run` rewrites it for every cosim
/// crate before building, so there is no state to keep in step.
const BUILD_RS: &str = r#"// Auto-generated by vw — safe to regenerate, and regenerated by `vw bench run`.
//
// A cosim testbench is a cdylib the simulator dlopens, so it has to be linked
// against the GPI libraries `rust-cosim` builds. `rust-cosim` declares
// `links = "cocotb"` and publishes their location as `DEP_COCOTB_TARGET_DIR`,
// which cargo hands to its dependents' build scripts — this one.
use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let libs_dir = PathBuf::from(env::var("DEP_COCOTB_TARGET_DIR").expect(
        "DEP_COCOTB_TARGET_DIR is not set — rust-cosim must be a dependency \
         of this crate",
    ));

    if !libs_dir.exists() {
        panic!(
            "the cocotb GPI libraries are not at {}.\n\
             Build rust-cosim first, or run this through `vw bench run`.",
            libs_dir.display(),
        );
    }

    let libs_dir = libs_dir.to_str().expect("GPI library path is not UTF-8");

    println!("cargo:rustc-link-arg=-L{libs_dir}");
    println!("cargo:rustc-link-arg=-lgpi");
    println!("cargo:rustc-link-arg=-lcocotbvhpi_nvc");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{libs_dir}");

    // `vhpi_assert` is the simulator's, resolved when nvc dlopens this. A
    // Linux shared library links with it undefined; the macOS linker refuses
    // to unless told that is the intent.
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-arg=-Wl,-undefined,dynamic_lookup");
    }
}
"#;

/// The first line of a `build.rs` this wrote, and the only thing that makes
/// it safe to rewrite one.
const BUILD_RS_MARKER: &str = "// Auto-generated by vw";

/// What a cosim bench ignores.
const GITIGNORE: &str = "\
# Auto-generated by vw and rewritten before every run — not worth committing.
build.rs

/target/
";

/// Create a Rust cosim testbench.
pub fn init(
    workspace_dir: &Utf8Path,
    name: &str,
    dut: Option<&str>,
    clock_hz: Option<f64>,
    vhdl_std: VhdlStandard,
) -> Result<Created> {
    // The name is a directory and a crate name, never a VHDL entity — the
    // entity is the design's — so it is as free as a mixed-signal bench's.
    super::check_crate_name(name)?;

    let dut = dut
        .map(|d| super::entity::load(workspace_dir, d, vhdl_std))
        .transpose()?;
    // Only worth reading the design's type declarations when there is an
    // entity whose ports might use them.
    let types = match &dut {
        Some(_) => super::entity::design_types(workspace_dir, vhdl_std)?,
        None => super::entity::DesignTypes::default(),
    };
    let clock = clock_hz.unwrap_or(DEFAULT_CLOCK_HZ);

    let mut files = super::workspace::ensure_bench_workspace(workspace_dir)?;

    let bench_dir = workspace_dir.join("bench").join(name);
    super::check_available(&bench_dir)?;
    std::fs::create_dir_all(bench_dir.join("src").as_std_path())?;

    let config = bench_dir.join("cosim.toml");
    write_new_file(&config, &render_config(name, dut.as_ref(), &types))?;
    files.push(config);

    let manifest = bench_dir.join("Cargo.toml");
    write_new_file(&manifest, &render_manifest(name))?;
    files.push(manifest);

    let lib = bench_dir.join("src").join("lib.rs");
    write_new_file(&lib, &render_driver(name, dut.as_ref(), &types, clock)?)?;
    files.push(lib);

    files.extend(ensure_scaffold(&bench_dir)?);

    let registered = super::workspace::register_member(workspace_dir, name)?;

    Ok(Created {
        name: name.to_string(),
        files,
        registered,
        next_steps: next_steps(name, dut.as_ref(), &types),
    })
}

fn next_steps(
    name: &str,
    dut: Option<&EntityInterface>,
    types: &DesignTypes,
) -> Vec<String> {
    let mut steps = Vec::new();
    match dut {
        Some(dut) => {
            steps.push(format!(
                "write the checks in `test()` in `bench/{name}/src/lib.rs` — \
                 every one of {}'s ports already has a handle on `Tb`",
                dut.name,
            ));
            let awkward: Vec<String> = plan_handles(dut, types)
                .into_iter()
                .filter(|h| h.reach != Reach::Bits)
                .map(|h| h.signal)
                .collect();
            if !awkward.is_empty() {
                steps.push(format!(
                    "check {}: an integer or composite signal has no bit \
                     string a driver can read, so `bench/{name}/src/lib.rs` \
                     leaves {} out of `quiesce`",
                    awkward.join(", "),
                    if awkward.len() == 1 { "it" } else { "them" },
                ));
            }
            if dut.generics.iter().any(|g| g.default.is_none()) {
                steps.push(format!(
                    "give the generics in `bench/{name}/cosim.toml` their \
                     values — the design declares them without defaults, and \
                     with no wrapper there is nowhere else to set them"
                ));
            }
        }
        None => steps.push(format!(
            "name the design entity in `bench/{name}/cosim.toml`, or re-run \
             with `--dut <entity>` to have the handles generated too"
        )),
    }
    steps.push(format!("run it with `vw bench run {name}`"));
    steps
}

/// Write the files a cosim crate needs but does not own.
fn ensure_scaffold(bench_dir: &Utf8Path) -> Result<Vec<Utf8PathBuf>> {
    let mut written = Vec::new();
    for (path, contents) in [
        (bench_dir.join("build.rs"), BUILD_RS),
        (bench_dir.join(".gitignore"), GITIGNORE),
    ] {
        if write_file(&path, contents)? {
            written.push(path);
        }
    }
    Ok(written)
}

/// Put a cosim crate's `build.rs` back, if it is missing or is a stale copy
/// of one of ours.
///
/// Called for every cosim crate before a run. Two failures it exists to
/// prevent, both of which present as a link error with nothing in it about
/// `build.rs`: a crate created before this existed (or cleaned away by `git
/// clean -fdx`) has none at all, and one written by an older `vw` links
/// against the wrong thing.
///
/// A `build.rs` without the marker is somebody's — a bench that needs an
/// extra link flag, say — and is left exactly as it is. `.gitignore` is never
/// touched here either: a crate may well have one of its own, and repairing
/// a link error is no reason to overwrite it.
pub fn heal(bench_dir: &Utf8Path) -> Result<bool> {
    let path = bench_dir.join("build.rs");
    match std::fs::read_to_string(path.as_std_path()) {
        Ok(existing) if !existing.starts_with(BUILD_RS_MARKER) => Ok(false),
        _ => write_file(&path, BUILD_RS),
    }
}

/// Whether this directory holds a cosim testbench crate.
///
/// The `cdylib` is what makes it one: a crate under `bench/` that is not a
/// `cdylib` is a helper library (shared packet builders, register maps) which
/// is linked into the benches rather than loaded by the simulator, and giving
/// one a GPI-linking `build.rs` would break it. A directory with a
/// `mist.toml` is a mixed-signal bench, whose whole crate — `build.rs`
/// included — is generated from that file instead.
pub fn is_cosim_crate(dir: &Utf8Path) -> bool {
    if dir.join("mist.toml").exists() {
        return false;
    }
    let Ok(text) =
        std::fs::read_to_string(dir.join("Cargo.toml").as_std_path())
    else {
        return false;
    };
    let Ok(manifest) = text.parse::<toml::Value>() else {
        return false;
    };
    manifest.get("package").is_some()
        && manifest
            .get("lib")
            .and_then(|lib| lib.get("crate-type"))
            .and_then(toml::Value::as_array)
            .is_some_and(|kinds| {
                kinds.iter().any(|k| k.as_str() == Some("cdylib"))
            })
}

// ===========================================================================
// Working out what the driver can reach
// ===========================================================================

/// One handle on the generated `Tb`.
#[derive(Clone, Debug)]
struct Handle {
    /// The Rust field name: `bus_in_go`.
    field: String,
    /// How it reads in a message and a doc comment: `bus_in.go`.
    signal: String,
    /// The `get_child` chain from the top level down: `["bus_in", "go"]`.
    path: Vec<String>,
    /// The subtype it was declared with.
    subtype: String,
    /// Whether the driver owns it.
    driven: bool,
    reach: Reach,
}

/// Work out every signal the driver should hold a handle to.
///
/// A record port contributes one handle per element rather than one for
/// itself: the aggregate is not a value, and reading it crashes the GPI
/// layer. Nested records are followed down, to a depth no real design reaches
/// but a self-referential one cannot exceed.
fn plan_handles(dut: &EntityInterface, types: &DesignTypes) -> Vec<Handle> {
    let mut handles = Vec::new();
    for port in &dut.ports {
        expand(
            port.mode().is_driven(),
            &port.name,
            &port.subtype,
            vec![port.name.clone()],
            types,
            0,
            &mut handles,
        );
    }
    handles
}

fn expand(
    driven: bool,
    signal: &str,
    subtype: &str,
    path: Vec<String>,
    types: &DesignTypes,
    depth: usize,
    out: &mut Vec<Handle>,
) {
    // The depth cap is a guard against a source that declares a record
    // reachable from itself, which will not elaborate but should not hang
    // this either.
    if depth < 4 {
        if let Some(fields) = types.record(subtype) {
            for field in fields {
                let mut path = path.clone();
                path.push(field.name.clone());
                expand(
                    driven,
                    &format!("{signal}.{}", field.name),
                    &field.subtype,
                    path,
                    types,
                    depth + 1,
                    out,
                );
            }
            return;
        }
    }

    out.push(Handle {
        field: super::rust_field(&path.join("_")),
        signal: signal.to_string(),
        path,
        subtype: subtype.to_string(),
        driven,
        reach: types.reach(subtype),
    });
}

// ===========================================================================
// cosim.toml
// ===========================================================================

fn render_config(
    name: &str,
    dut: Option<&EntityInterface>,
    types: &DesignTypes,
) -> String {
    let mut out = String::from(
        "# Rust cosim testbench.\n\
         #\n\
         # The entity named here is the top level: nvc elaborates it as it \
         stands\n\
         # and the crate beside this file is the only thing driving it. There \
         is no\n\
         # VHDL harness.\n\
         \n",
    );

    match dut {
        Some(dut) => {
            out.push_str(&format!("entity = \"{}\"\n", dut.name));
        }
        None => {
            out.push_str(&format!(
                "# TODO: the design entity this bench drives.\n\
                 entity = \"TODO_{name}_entity\"\n",
            ));
        }
    }

    let Some(dut) = dut else {
        return out;
    };

    let awkward: Vec<Handle> = plan_handles(dut, types)
        .into_iter()
        .filter(|h| h.reach != Reach::Bits)
        .collect();
    if !awkward.is_empty() {
        out.push_str(
            "\n# Signals with no bit string a driver can read. An \
             integer port comes\n\
             # back empty, and an array of composites has no single value \
             that means\n\
             # anything. They have handles in src/lib.rs but are left out of \
             `quiesce`:\n\
             #\n",
        );
        for handle in &awkward {
            out.push_str(&format!(
                "#   {} : {}\n",
                handle.signal, handle.subtype,
            ));
        }
        out.push_str(
            "#\n\
             # To check one, add a VHDL entity wrapping this one that \
             presents it as a\n\
             # logic vector, and point `entity` at that instead.\n",
        );
    }

    if dut.generics.is_empty() {
        return out;
    }

    out.push_str(
        "\n# Generic overrides, applied at elaboration. With no wrapper there \
         is\n\
         # nowhere else to set them, so a generic the design declares without \
         a\n\
         # default has to have a value here or elaboration fails.\n\
         [generics]\n",
    );
    let width = dut.generics.iter().map(|g| g.name.len()).max().unwrap_or(0);
    for generic in &dut.generics {
        match &generic.default {
            // Commented out: the design's own default already applies, and an
            // entry here would be a second place to keep it up to date.
            Some(default) => out.push_str(&format!(
                "# {:width$} = \"{default}\"   # the design's default\n",
                generic.name,
            )),
            None => out.push_str(&format!(
                "{:width$} = \"{}\"   # TODO: no default in {}\n",
                generic.name,
                super::placeholder(generic, types)
                    .unwrap_or_else(|| "1".to_string()),
                dut.name,
            )),
        }
    }
    out
}

fn render_manifest(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

# The simulator dlopens this, so it has to be a C-ABI shared library rather
# than an rlib. Without this the crate builds and the bench then fails with
# nothing to load.
[lib]
crate-type = ["cdylib"]

[dependencies]
rust-cosim.workspace = true
futures.workspace = true
log.workspace = true
env_logger.workspace = true
"#
    )
}

// ===========================================================================
// src/lib.rs
// ===========================================================================

/// A `///` comment, one attribute per line.
///
/// `quote!` drops `//` comments — the lexer discards them before the macro
/// sees them — so everything a generated file has to say has to be said in
/// doc attributes, which `prettyplease` renders back as `///`.
fn doc(text: &str) -> TokenStream {
    let lines = text.lines().map(|line| {
        let line = if line.is_empty() {
            String::new()
        } else {
            format!(" {line}")
        };
        quote!(#[doc = #line])
    });
    quote!(#(#lines)*)
}

/// The same, as `//!`.
fn module_doc(text: &str) -> TokenStream {
    let lines = text.lines().map(|line| {
        let line = if line.is_empty() {
            String::new()
        } else {
            format!(" {line}")
        };
        quote!(#![doc = #line])
    });
    quote!(#(#lines)*)
}

fn render_driver(
    name: &str,
    dut: Option<&EntityInterface>,
    types: &DesignTypes,
    clock_hz: f64,
) -> Result<String> {
    let entity = dut.map(|d| d.name.as_str()).unwrap_or("the design");

    // nvc's time step is a femtosecond, and `Timer` counts steps. Getting
    // this wrong by a factor of a thousand is a bench that looks like it runs
    // and is a thousand times the wrong speed.
    let half_period_fs =
        Literal::u64_unsuffixed((0.5e15 / clock_hz).round() as u64);

    let header = module_doc(&format!(
        "Cosim testbench for `{entity}`.\n\
         \n\
         nvc elaborates `{entity}` as the top level and loads this library \
         beside\n\
         it. There is no VHDL harness: everything the design sees is driven \
         from\n\
         here, its clock included, so simulation time only advances when this\n\
         asks it to.\n\
         \n\
         Signals are looked up by name, so a port renamed in the design has \
         to be\n\
         renamed here too — the mismatch is a run-time `TestError`, not a \
         build\n\
         failure."
    ));

    let body = match dut {
        Some(dut) => with_dut(dut, types, &half_period_fs),
        None => without_dut(name),
    };

    let tokens = quote! {
        #header
        #![allow(dead_code)]

        use rust_cosim::handles::{SetAction, SimHandle};
        use rust_cosim::triggers::{ReadOnly, Timer};
        use rust_cosim::TestError;
        use std::future::Future;
        use std::pin::Pin;

        #body
    };

    let file =
        syn::parse2::<syn::File>(tokens).map_err(|e| VwError::CodeGen {
            message: format!("generated driver does not parse: {e}"),
        })?;
    Ok(prettyplease::unparse(&file))
}

/// The part of the driver that exists whether or not there is a design to
/// drive: getting the simulator moving, and the entry point.
fn prime_fn() -> TokenStream {
    let docs = doc(
        "Give the simulator something to do before anything else is awaited.\n\
         \n\
         With no VHDL harness, nothing in the design schedules an event of \
         its\n\
         own. Unless a timed callback is registered first, the simulator \
         finds no\n\
         work at time zero and ends the run before the test has started.",
    );
    quote! {
        #docs
        async fn prime() {
            Timer::new(1).await;
        }
    }
}

fn without_dut(name: &str) -> TokenStream {
    let prime = prime_fn();
    let starting = Literal::string(&format!("{name} starting"));
    let test_docs = doc("What this bench checks.\n\
         \n\
         TODO: `cosim.toml` does not name a design entity yet. Set one — or \
         re-run\n\
         `vw cosim init` with `--dut <entity>` — and the handles for its \
         signals\n\
         will be generated alongside this.");
    quote! {
        #test_docs
        async fn test(dut: &SimHandle) -> Result<(), TestError> {
            let _ = dut;
            Ok(())
        }

        #prime

        #[no_mangle]
        pub fn testbench_main(
            dut: SimHandle,
        ) -> Pin<Box<dyn Future<Output = Result<(), TestError>>>> {
            env_logger::Builder::from_env(
                env_logger::Env::default().default_filter_or("info"),
            )
            .init();

            Box::pin(async move {
                log::info!(#starting);
                prime().await;
                test(&dut).await?;
                Ok(())
            })
        }
    }
}

fn with_dut(
    dut: &EntityInterface,
    types: &DesignTypes,
    half_period_fs: &Literal,
) -> TokenStream {
    let handles = plan_handles(dut, types);
    let clock = dut
        .clock()
        .and_then(|c| handles.iter().find(|h| h.signal == c.name));
    let reset = dut.reset().and_then(|r| {
        handles.iter().find(|h| h.signal == r.name).map(|h| (r, h))
    });

    let struct_docs = doc(&format!("Handles to `{}`'s signals.", dut.name));
    let fields = handles.iter().map(|handle| {
        let field = format_ident!("{}", handle.field);
        let note = match handle.reach {
            Reach::Bits => String::new(),
            Reach::Integer => {
                ", reads back empty — integers have no bit string".to_string()
            }
            // Only reachable past the recursion cap; a record within reach
            // was expanded into its elements above.
            Reach::Record | Reach::Unknown => {
                ", not a bit string this can size".to_string()
            }
        };
        let docs = doc(&format!(
            "`{}` — {} ({}{note})",
            handle.signal,
            if handle.driven {
                "driven from here"
            } else {
                "driven by the design"
            },
            handle.subtype,
        ));
        quote! { #docs pub #field: SimHandle }
    });

    let lookups = handles.iter().map(|handle| {
        let field = format_ident!("{}", handle.field);
        // A record element is reached through its port, one `get_child` per
        // step: the aggregate handle exists but is not a value.
        let mut expr = quote! { dut };
        for step in &handle.path {
            let step = Literal::string(step);
            expr = quote! { #expr.get_child(#step)? };
        }
        quote! { #field: #expr }
    });

    let new_docs = doc("Look every signal up by name.\n\
         \n\
         A record element is reached through its port — `bus.field`, not\n\
         `bus_field` — because that is where the simulator keeps it.");
    let quiesce = quiesce_fn(&handles);
    let tick = clock.map(|clock| tick_fn(clock, half_period_fs));
    let reset_fn = reset
        .filter(|_| clock.is_some())
        .map(|(port, handle)| reset_fn(port, handle));
    let helpers = helper_fns();
    let prime = prime_fn();

    let test_docs = doc("What this bench checks.\n\
         \n\
         TODO: this is the part that is yours. Drive an input with\n\
         `tb.drive()`, step time with `tb.tick()`, and read an output with\n\
         `tb.read_bit()` or `tb.read_int()`.\n\
         \n\
         Returning `Err` is what fails the bench. A panic is reported as a\n\
         crash, and an `assert!` that fires is a panic.");

    let starting = Literal::string(&format!("{} starting", dut.name));
    let complete = Literal::string(&format!("{} complete", dut.name));
    let reset_call = reset_fn.is_some().then(|| quote! { tb.reset().await; });

    quote! {
        #struct_docs
        pub struct Tb {
            #(#fields,)*
        }

        impl Tb {
            #new_docs
            fn new(dut: &SimHandle) -> Result<Self, TestError> {
                Ok(Self { #(#lookups,)* })
            }

            #quiesce
            #tick
            #reset_fn
            #helpers
        }

        #test_docs
        async fn test(tb: &Tb) -> Result<(), TestError> {
            let _ = tb;
            Ok(())
        }

        #prime

        #[no_mangle]
        pub fn testbench_main(
            dut: SimHandle,
        ) -> Pin<Box<dyn Future<Output = Result<(), TestError>>>> {
            env_logger::Builder::from_env(
                env_logger::Env::default().default_filter_or("info"),
            )
            .init();

            Box::pin(async move {
                log::info!(#starting);
                let tb = Tb::new(&dut)?;

                prime().await;
                tb.quiesce();
                #reset_call

                test(&tb).await?;

                log::info!(#complete);
                Ok(())
            })
        }
    }
}

fn quiesce_fn(handles: &[Handle]) -> TokenStream {
    let writes = handles.iter().filter(|h| h.driven).filter_map(|handle| {
        let field = format_ident!("{}", handle.field);
        match handle.reach {
            Reach::Bits => Some(quote! { self.drive(&self.#field, 0); }),
            Reach::Integer => Some(quote! {
                self.#field.set_value_int(0, SetAction::NoDelay);
            }),
            // Nothing sensible to write: see the note on the handle.
            Reach::Record | Reach::Unknown => None,
        }
    });
    let docs = doc("Put every input at a defined value.\n\
         \n\
         An input left at 'U' propagates into the design and buries the run \
         in\n\
         numeric_std metavalue warnings long before any check fails.");
    quote! {
        #docs
        pub fn quiesce(&self) {
            #(#writes)*
        }
    }
}

fn tick_fn(clock: &Handle, half_period_fs: &Literal) -> TokenStream {
    let field = format_ident!("{}", clock.field);
    let docs = doc("Drive one clock period.\n\
         \n\
         Nothing else drives the design's clock — it is the top level — so\n\
         simulation time advances when this is called and not otherwise. \
         Inputs\n\
         set before it are what the design sees on the rising edge.");
    quote! {
        #docs
        pub async fn tick(&self) {
            self.#field.set_value_binstr("1", SetAction::NoDelay);
            Timer::new(#half_period_fs).await;
            self.#field.set_value_binstr("0", SetAction::NoDelay);
            Timer::new(#half_period_fs).await;
        }
    }
}

fn reset_fn(port: &Interface, handle: &Handle) -> TokenStream {
    let field = format_ident!("{}", handle.field);
    let (asserted, released) = if port.is_active_low_reset() {
        ("0", "1")
    } else {
        ("1", "0")
    };
    let asserted = Literal::string(asserted);
    let released = Literal::string(released);
    let docs = doc(
        "Hold the design in reset for four clock periods, then release it.",
    );
    quote! {
        #docs
        pub async fn reset(&self) {
            self.#field.set_value_binstr(#asserted, SetAction::NoDelay);
            for _ in 0..4 {
                self.tick().await;
            }
            self.#field.set_value_binstr(#released, SetAction::NoDelay);
            self.tick().await;
        }
    }
}

fn helper_fns() -> TokenStream {
    let drive_docs = doc(
        "Drive a signal with an unsigned value, whatever its width.\n\
         \n\
         The bit string is sized from the signal itself, so this works the \
         same\n\
         on a `std_logic`, a `std_logic_vector`, a subtype of either, and a \
         port\n\
         whose width comes from a generic — none of which have to be known \
         here.",
    );
    let bit_docs = doc("Read a logic signal as a bit.\n\
         \n\
         Anything that is not '1' — 'U' and 'X' included — reads as false, \
         which\n\
         is what a check wants.");
    let int_docs = doc("Read a logic vector as an unsigned integer.\n\
         \n\
         Fails rather than guessing if any bit is a metavalue, since a\n\
         half-undefined vector is not a number and silently reading it as one\n\
         turns a real bug into a passing check.");
    quote! {
        #drive_docs
        pub fn drive(&self, signal: &SimHandle, value: u64) {
            let width = signal.get_range().max(1);
            let bits = format!("{value:0width$b}");
            signal.set_value_binstr(
                &bits[bits.len() - width..],
                SetAction::NoDelay,
            );
        }

        #bit_docs
        pub async fn read_bit(&self, signal: &SimHandle) -> bool {
            ReadOnly::new().await;
            signal.get_value_binstr().as_deref() == Some("1")
        }

        #int_docs
        pub async fn read_int(
            &self,
            signal: &SimHandle,
        ) -> Result<u64, TestError> {
            ReadOnly::new().await;
            let bits = signal.get_value_binstr().unwrap_or_default();
            u64::from_str_radix(&bits, 2).map_err(|_| {
                TestError::ValueError(format!("not a number: '{bits}'"))
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bench_init::entity::{PortMode, RecordField};

    fn port(name: &str, mode: PortMode, subtype: &str) -> Interface {
        Interface {
            name: name.to_string(),
            mode: Some(mode),
            subtype: subtype.to_string(),
            default: None,
        }
    }

    fn dut() -> EntityInterface {
        EntityInterface {
            name: "flit_fifo".to_string(),
            file: std::path::PathBuf::from("hdl/flit_fifo.vhd"),
            context: Vec::new(),
            generics: vec![
                Interface {
                    name: "DATA_W".to_string(),
                    mode: None,
                    subtype: "positive".to_string(),
                    default: Some("32".to_string()),
                },
                Interface {
                    name: "FAST_READ".to_string(),
                    mode: None,
                    subtype: "boolean".to_string(),
                    default: None,
                },
            ],
            ports: vec![
                port("clk", PortMode::In, "std_logic"),
                port("rstn", PortMode::In, "std_logic"),
                port(
                    "write_data",
                    PortMode::In,
                    "std_logic_vector(DATA_W - 1 downto 0)",
                ),
                // A subtype: nothing about its width is knowable from here.
                port("tap", PortMode::In, "Nibble"),
                // A record: one handle per element, not one for the whole.
                port("bus_in", PortMode::In, "lrq"),
                port("empty", PortMode::Out, "std_logic"),
                // An integer: drivable, but it does not read back.
                port("level", PortMode::Out, "natural"),
            ],
        }
    }

    fn types() -> DesignTypes {
        let mut types = DesignTypes::default();
        types
            .subtypes
            .insert("nibble".into(), "std_logic_vector(3 downto 0)".into());
        types.records.insert(
            "lrq".into(),
            vec![
                RecordField {
                    name: "valid".into(),
                    subtype: "std_logic".into(),
                },
                RecordField {
                    name: "data".into(),
                    subtype: "Nibble".into(),
                },
            ],
        );
        types
    }

    fn driver() -> String {
        render_driver("fifo", Some(&dut()), &types(), 100e6).unwrap()
    }

    /// The generated file has to be valid Rust. It is built as a token tree
    /// and parsed before it is written, so this can only fail loudly.
    #[test]
    fn the_driver_is_syntactically_valid_rust() {
        syn::parse_file(&driver()).expect("generated driver parses");
    }

    /// `quote!` drops `//` comments — the lexer discards them before the
    /// macro sees them — so everything the file has to explain has to survive
    /// as a doc attribute.
    #[test]
    fn the_explanations_survive_code_generation() {
        let text = driver();
        assert!(text.contains("//! Cosim testbench for `flit_fifo`."));
        assert!(text.contains("/// Drive one clock period."));
        assert!(text.contains("TODO: this is the part that is yours."));
    }

    /// A record port is reached one element at a time: the aggregate handle
    /// exists but is not a value, and reading it crashes the GPI layer.
    #[test]
    fn record_ports_become_one_handle_per_element() {
        let text = driver();

        assert!(text.contains("pub bus_in_valid: SimHandle"));
        assert!(text.contains("pub bus_in_data: SimHandle"));
        assert!(
            text.contains(
                r#"bus_in_valid: dut.get_child("bus_in")?.get_child("valid")?"#
            ),
            "the element is reached through its port",
        );
        // And never the aggregate on its own.
        assert!(!text.contains("pub bus_in: SimHandle"));
    }

    /// A subtype needs no special handling as long as nothing assumes a
    /// width: the signal knows its own.
    #[test]
    fn subtype_ports_are_driven_by_their_own_width() {
        let text = driver();
        assert!(text.contains("pub tap: SimHandle"));
        assert!(text.contains("self.drive(&self.tap, 0);"));
        assert!(text.contains("let width = signal.get_range().max(1);"));
    }

    /// nvc counts in femtoseconds and `Timer` counts nvc's steps. A factor of
    /// a thousand here is a bench that runs at the wrong speed and looks fine.
    #[test]
    fn the_clock_period_is_in_femtoseconds() {
        let text =
            render_driver("fifo", Some(&dut()), &types(), 100e6).unwrap();
        assert!(
            text.contains("Timer::new(5000000)"),
            "100 MHz is a 5 ns half period, which is 5e6 fs",
        );

        let text =
            render_driver("fifo", Some(&dut()), &types(), 26.5625e9).unwrap();
        assert!(text.contains("Timer::new(18824)"));
    }

    /// The first thing awaited must be a timed callback: without one the
    /// simulator finds nothing to do at time zero and ends before the test.
    #[test]
    fn the_simulator_is_primed_before_anything_else() {
        let text = driver();
        let prime = text.find("prime().await;").expect("primed");
        let quiesce = text.find("tb.quiesce();").expect("quiesced");
        let test = text.find("test(&tb).await?;").expect("test runs");
        assert!(prime < quiesce && quiesce < test);
        assert!(text.contains("Timer::new(1).await;"));
    }

    /// Everything the driver owns starts at a defined value, nothing it does
    /// not own is touched, and nothing it cannot size is guessed at.
    #[test]
    fn the_driver_quiesces_only_what_it_can() {
        let text = driver();
        assert!(text.contains("self.drive(&self.write_data, 0);"));
        assert!(text.contains("self.drive(&self.bus_in_valid, 0);"));
        // An output is the design's to drive.
        assert!(!text.contains("self.drive(&self.empty"));
        // ...and `level` is an output too, so it is not driven either.
        assert!(!text.contains("self.level.set_value_int"));
    }

    /// An active-low reset is asserted low and released high. Backwards, the
    /// design never leaves reset and the bench hangs.
    #[test]
    fn reset_polarity_follows_the_port_name() {
        let text = driver();
        let reset = text.find("pub async fn reset").expect("reset");
        let asserted = text[reset..]
            .find(r#"self.rstn.set_value_binstr("0""#)
            .expect("asserted");
        let released = text[reset..]
            .find(r#"self.rstn.set_value_binstr("1""#)
            .expect("released");
        assert!(asserted < released);
    }

    /// A generic with no default has to be set somewhere, and with no wrapper
    /// `cosim.toml` is the only somewhere there is.
    #[test]
    fn generics_without_defaults_are_surfaced() {
        let text = render_config("fifo", Some(&dut()), &types());
        let parsed: crate::cosim::CosimConfig =
            toml::from_str(&text).expect("valid toml");

        assert_eq!(parsed.entity, "flit_fifo");
        assert!(
            parsed.generics.contains_key("FAST_READ"),
            "a generic with no default must be set or elaboration fails",
        );
        assert!(
            !parsed.generics.contains_key("DATA_W"),
            "one with a default is left to the design, not restated here",
        );
    }

    /// The config says which signals the driver could not size, or their
    /// absence from `quiesce` looks like an oversight.
    #[test]
    fn the_config_names_the_signals_it_could_not_size() {
        let text = render_config("fifo", Some(&dut()), &types());
        assert!(text.contains("level : natural"));
        // ...and does not complain about the ones that are fine.
        assert!(!text.contains("tap : Nibble"));
        assert!(!text.contains("write_data :"));
    }

    /// Without an entity there is still a parseable config and a driver that
    /// builds.
    #[test]
    fn a_bench_with_no_dut_still_stands_on_its_own() {
        let text = render_config("fifo", None, &DesignTypes::default());
        let parsed: crate::cosim::CosimConfig =
            toml::from_str(&text).expect("valid toml");
        assert!(parsed.entity.starts_with("TODO_"));

        let driver =
            render_driver("fifo", None, &DesignTypes::default(), 100e6)
                .unwrap();
        syn::parse_file(&driver).expect("generated driver parses");
        assert!(driver.contains("prime().await;"));
    }

    /// The crate has to be a cdylib or there is nothing for the simulator to
    /// load, and it has to reach rust-cosim through the bench workspace.
    #[test]
    fn the_manifest_builds_something_the_simulator_can_load() {
        let text = render_manifest("fifo");
        assert!(text.contains(r#"crate-type = ["cdylib"]"#));
        assert!(text.contains("rust-cosim.workspace = true"));
    }

    fn crate_at(kind: &str) -> (tempfile::TempDir, Utf8PathBuf) {
        let guard = tempfile::tempdir().unwrap();
        let dir =
            Utf8PathBuf::from_path_buf(guard.path().to_path_buf()).unwrap();
        std::fs::write(dir.join("Cargo.toml"), kind).unwrap();
        (guard, dir)
    }

    /// A `cdylib` under `bench/` is a testbench. A plain library is shared
    /// helper code the benches link against, and giving one a GPI-linking
    /// `build.rs` would break it.
    #[test]
    fn only_cdylib_crates_count_as_cosim_benches() {
        let (_g, bench) = crate_at(
            "[package]\nname = \"b\"\n[lib]\ncrate-type = [\"cdylib\"]\n",
        );
        assert!(is_cosim_crate(&bench));

        let (_g, helper) = crate_at("[package]\nname = \"helpers\"\n");
        assert!(!is_cosim_crate(&helper));

        let (_g, manifest_only) = crate_at("[workspace]\nmembers = []\n");
        assert!(!is_cosim_crate(&manifest_only));

        // A mixed-signal bench's whole crate is generated from its mist.toml,
        // build.rs included, so it is not this code's business.
        let (_g, mixed) = crate_at(
            "[package]\nname = \"m\"\n[lib]\ncrate-type = [\"cdylib\"]\n",
        );
        std::fs::write(mixed.join("mist.toml"), "").unwrap();
        assert!(!is_cosim_crate(&mixed));
    }

    /// The failure this exists for: a clone or a `git clean -fdx` leaves a
    /// cosim crate with no `build.rs`, and the bench then fails at link time
    /// with an error that says nothing about it.
    #[test]
    fn a_missing_build_script_is_put_back() {
        let (_g, dir) = crate_at("[package]\nname = \"b\"\n");

        assert!(heal(&dir).unwrap());
        assert!(dir.join("build.rs").exists());
        // Already right — nothing rewritten, so cargo's incremental build
        // stays hot.
        assert!(!heal(&dir).unwrap());
    }

    /// A `build.rs` somebody wrote — a bench needing an extra link flag — is
    /// never replaced. Repairing a link error is no reason to throw away work.
    #[test]
    fn a_hand_written_build_script_is_left_alone() {
        let (_g, dir) = crate_at("[package]\nname = \"b\"\n");
        std::fs::write(dir.join("build.rs"), "fn main() { /* mine */ }")
            .unwrap();

        assert!(!heal(&dir).unwrap());
        assert!(std::fs::read_to_string(dir.join("build.rs"))
            .unwrap()
            .contains("mine"));
    }

    /// One written by an older vw is ours to bring up to date.
    #[test]
    fn a_stale_generated_build_script_is_replaced() {
        let (_g, dir) = crate_at("[package]\nname = \"b\"\n");
        std::fs::write(
            dir.join("build.rs"),
            "// Auto-generated by vw — from some earlier version\n",
        )
        .unwrap();

        assert!(heal(&dir).unwrap());
        assert_eq!(
            std::fs::read_to_string(dir.join("build.rs")).unwrap(),
            BUILD_RS,
        );
    }
}
