# Auto-generated by vw
# Associative array of dependency VHDL files
# Keys: library names, Values: lists of VHDL files
# Paths below interpolate $vw_deps_dir at source time so the
# resulting lists contain absolute, ready-to-use file paths.

if {[info exists ::env(VW_DEPS_DIR)] && $::env(VW_DEPS_DIR) ne ""} {
    set vw_deps_dir $::env(VW_DEPS_DIR)
} elseif {[info exists ::env(USERPROFILE)] && $::env(USERPROFILE) ne ""} {
    set vw_deps_dir [file join $::env(USERPROFILE) .vw deps]
} elseif {[info exists ::env(HOME)] && $::env(HOME) ne ""} {
    set vw_deps_dir [file join $::env(HOME) .vw deps]
} else {
    error "vw: unable to locate dependency cache; set VW_DEPS_DIR or HOME"
}

set dep_files(quartz) [list \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/dcfifo_mixed_xpm.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/dcfifo_xpm.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/sims/fifos_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/sims/fifos_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/sims/fifos_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axilite_if_2k19_helper_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_interconnect_2k8.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axilite_if_2k8_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axist_if_2k19_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_interconnect.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_common_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_target_txn.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axilite_if_2k19_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil8_resizer.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_txn/spi_txn_mgr.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_nor_regs.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_nor_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_nor_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/espi_txn/espi_flash_txn_mgr.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/sims/spi_nor_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/sims/spi_nor_tb_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/sims/spi_nor_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/link/spi_clk_gen.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/link/spi_link.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/mixed_width_adaptor.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/mixed_width_simple_dpr.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/sims/memories_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/sims/memories_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/sims/memories_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/dual_clock_simple_dpr.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/info/info.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/info/info_2k8.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/bacd.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/async_reset_bridge.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/tacd.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/sims/synchronizers_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/sims/synchronizers_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/meta_sync.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_status.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_io.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_target_common.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_tgt_sim_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_controller_model.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_tgt_sim_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ibc_control.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/tx_path/ignition_tx.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/rx_path/pkt_parsing.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/rx_path/ignit_rx_pipe.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/stm32h7_fmc_target_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/stm32h7_fmc_target.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/sims/fmc_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/sims/fmc_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/sims/fmc_tb_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/model/stm32h7_fmc_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/model/stm32h7_fmc_model.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/calc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/transforms_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/time_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/sims/utilities_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/interfaces/tristate_if_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/countdown/sims/countdown_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/countdown/sims/countdown_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/countdown/countdown.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/strobe/sims/strobe_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/strobe/sims/strobe_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/strobe/strobe.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ls_xcvr/aligner_10bk28_5.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ls_xcvr/ls_serdes.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/8b10b/encode_8b10b.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/8b10b/decode_8b10b.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/8b10b/helper_8b10b_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/arbiter.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/arbiter_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/sims/arbiter_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/sims/arbiter_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/sims/arbiter_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/espi_spec_regs.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/flash_channel/flash_channel_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/flash_channel/flash_channel.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sys_regs/espi_regs.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/peripheral_channel/uart_channel_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/peripheral_channel/uart_channel_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/link_layer.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/alert_gen.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/qspi_link_layer_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/link_layer_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/dbg_link_faker.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/cmd_sizer.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/vwire_channel/vwire_block.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/espi_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/espi_tb_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/espi_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/models/espi_dbg_vc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/models/fake_flash_txn_mgr.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/models/espi_controller_vc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/response_processor.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/espi_protocol_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/link_to_txn_bridge.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/txn_layer_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/espi_base_types_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/command_processor.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/espi_target_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/pipeline/skidbuffer.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/spi_to_axi.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/spi_axi_controller_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/sims/spi_axi_tb_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/sims/spi_axi_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/sims/spi_axi_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/spi_axi_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/spi_target_phy/spi_target_phy.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ice40primitives/ice40_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ice40primitives/ice40_lvds_in.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/crc/crc8atm_8wide.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/crc/crc_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/crc/crc8autostar_8wide.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/oximux16_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/sims/oximux16_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/sims/oximux16_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/sims/oximux16_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/oximux16_function.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/pca9545ish_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/pca9545ish_function.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/pca9545_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/common/i2c_common_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/common/i2c_glitch_filter.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/i2c_base_types_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/i2c_target_phy.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/sims/i2c_target_phy_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/sims/i2c_target_phy_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/sims/i2c_target_phy_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/i2c_phy_consolidator.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_regs.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_function.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/sims/i2c_pca9506ish_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/sims/i2c_pca9506ish_sim_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/sims/i2c_pca9506ish_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/link_layer/i2c_ctrl_link_layer.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/i2c_ctrl_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/txn_layer/i2c_ctrl_txn_layer.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/regs/i2c_ctrl_regs.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/fifo_uart/axi_fifo_st_uart.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/sims/uart_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/sims/uart_tb_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/sims/uart_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/base_uart/axi_st_uart.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sgpio_top.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sgpio_shift_in.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sgpio_shift_out.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sims/sgpio_th.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sims/sgpio_tb.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/gpio/sim_gpio.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/gpio/gpio_msg_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_controller/i2c_ctrlr_vc.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_controller/i2c_ctrlr_vc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/spi_controller/spi_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/spi_controller/spi_slave.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/spi_controller/spi_master.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_target/i2c_target_vc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_target/i2c_target_vc.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/qspi_controller/qspi_controller_vc.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/qspi_controller/qspi_vc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/I2c_cmd/i2c_cmd_vc.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/I2c_cmd/i2c_cmd_vc_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/sim_gpio.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/basic_stream_pkg.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/basic_source.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/sims/tb_basic_stream.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/sims/th_basic_stream.vhd \
    $vw_deps_dir/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/basic_sink.vhd
]

