// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! Emit an htcl wrapper proc for a parsed [`ManPage`].
//!
//! Shape, for a command `add_files`:
//!
//! ```htcl
//! # Preserve the underlying Vivado command so the wrapper can forward
//! # to it after shadowing the global name.
//! if {[info commands __viv_add_files] eq "" && [info commands add_files] ne ""} {
//!   rename add_files __viv_add_files
//! }
//!
//! ## Adds one or more source files ...
//! proc add_files {
//!   ## (Optional) The fileset to add to.
//!   @default("") fileset
//!   ## (Optional) Do not recurse ...
//!   @enum(0, 1) @default(0) norecurse
//!   ## Positional operands ...
//!   @default("") operands
//! } {
//!   set cmd [list __viv_add_files]
//!   if {$fileset ne ""} { lappend cmd -fileset $fileset }
//!   if {$norecurse} { lappend cmd -norecurse }
//!   if {$operands ne ""} { lappend cmd {*}$operands }
//!   return [{*}$cmd]
//! }
//! ```
//!
//! The wrapper keeps the command's natural name and shadows the
//! builtin; a guarded `rename` stashes the original under
//! `<prefix><name>` so the body forwards to it without recursing. All
//! arguments are addressed by keyword (`-fileset value`); boolean flags
//! take a `0`/`1` value at the htcl layer and lower to flag
//! presence/absence on the Vivado command line.

use std::fmt::Write;

use vw_htcl::emit::{Command, Doc, Item, Word};

use crate::model::{ArgKind, Argument, ManPage};

#[derive(Clone, Debug)]
pub struct GenerateOptions {
    /// Prefix for the stashed original command (`rename add_files
    /// __viv_add_files`).
    pub rename_prefix: String,
    /// Emit each command's `See Also` list as a doc-comment footer.
    pub include_see_also: bool,
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            rename_prefix: "__viv_".to_string(),
            include_see_also: true,
        }
    }
}

/// Generate the htcl wrapper text for `page`.
pub fn generate(page: &ManPage, opts: &GenerateOptions) -> String {
    let cmd = &page.name;
    let orig = format!("{}{}", opts.rename_prefix, page.name);

    let mut out = String::new();
    writeln!(
        out,
        "# Generated by `vw htcl-cmd generate` from the Vivado command \
         reference."
    )
    .unwrap();
    writeln!(out, "# Do not edit by hand.").unwrap();
    writeln!(out).unwrap();

    // Guarded rename: stash the builtin so the wrapper can forward to
    // it. Guard keeps it a no-op if the command is missing or already
    // renamed (e.g. the file is sourced twice in one Vivado session).
    writeln!(
        out,
        "# Preserve the underlying Vivado `{cmd}` command so this typed \
         wrapper"
    )
    .unwrap();
    writeln!(out, "# can forward to it after shadowing the global name.")
        .unwrap();
    writeln!(
        out,
        "if {{[info commands {orig}] eq \"\" && [info commands {cmd}] ne \
         \"\"}} {{"
    )
    .unwrap();
    writeln!(out, "  rename {cmd} {orig}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Proc doc comment: the command Description, then a See-Also footer.
    emit_proc_doc(&mut out, page, opts);

    // Proc args (structured) and body (compact Tcl).
    let args = build_args(page);
    let body = build_body(&orig, page);
    emit_proc(&mut out, cmd, &args, &body);

    // Trim trailing whitespace line-by-line (empty doc comments emit a
    // trailing space) and guarantee a single trailing newline.
    let mut cleaned: String = out
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    cleaned.push('\n');
    cleaned
}

/// Write the proc-level doc comments (the command description + a
/// `See also:` footer) immediately above where the `proc` line will
/// go, so they attach to it.
fn emit_proc_doc(out: &mut String, page: &ManPage, opts: &GenerateOptions) {
    let mut wrote = false;
    let mut blanks = 0;
    for line in &page.description {
        let line = sanitize_doc(line);
        if line.is_empty() {
            blanks += 1;
            continue;
        }
        // Collapse runs of blank lines into a single `##` separator.
        if wrote && blanks > 0 {
            writeln!(out, "##").unwrap();
        }
        blanks = 0;
        writeln!(out, "## {line}").unwrap();
        wrote = true;
    }
    if !wrote {
        writeln!(out, "## Wrapper for the Vivado `{}` command.", page.name)
            .unwrap();
    }
    if opts.include_see_also && !page.see_also.is_empty() {
        writeln!(out, "##").unwrap();
        writeln!(out, "## See also: {}", page.see_also.join(", ")).unwrap();
    }
}

/// Build the structured arg list as an emit [`Doc`]: per-argument doc
/// comments followed by an `@attr… ident` declaration.
fn build_args(page: &ManPage) -> Doc {
    let mut doc = Doc::new();
    for (i, arg) in page.arguments.iter().enumerate() {
        if i > 0 {
            doc.push(Item::Blank);
        }
        for line in &arg.description {
            let line = sanitize_doc(line);
            if line.is_empty() {
                doc.push(Item::DocComment(String::new()));
            } else {
                doc.push(Item::DocComment(line));
            }
        }
        doc.push(Item::Command(Command {
            doc_comments: Vec::new(),
            words: arg_attr_words(arg),
            body: None,
        }));
    }
    doc
}

/// The attribute words + identifier for one argument declaration.
fn arg_attr_words(arg: &Argument) -> Vec<Word> {
    let mut words = Vec::new();
    match arg.kind {
        ArgKind::Boolean => {
            words.push(Word::Raw("@enum(0, 1)".to_string()));
            words.push(Word::Raw("@default(0)".to_string()));
        }
        ArgKind::Value | ArgKind::Positional => {
            // Required args carry no default, so htcl forces the caller
            // to supply them; optional args default to the empty string
            // sentinel that the body treats as "omitted".
            if !arg.required {
                words.push(Word::Raw("@default(\"\")".to_string()));
            }
        }
    }
    words.push(Word::Bare(arg.ident.clone()));
    words
}

/// Build the proc body: assemble the forwarded command incrementally,
/// then invoke the stashed original by list-expansion.
fn build_body(orig: &str, page: &ManPage) -> String {
    let mut body = String::new();
    writeln!(body, "set cmd [list {orig}]").unwrap();
    for arg in &page.arguments {
        let id = &arg.ident;
        match arg.kind {
            ArgKind::Boolean => {
                let flag = arg.flag.as_deref().unwrap_or(id);
                writeln!(body, "if {{${id}}} {{ lappend cmd -{flag} }}")
                    .unwrap();
            }
            ArgKind::Value => {
                let flag = arg.flag.as_deref().unwrap_or(id);
                if arg.required {
                    writeln!(body, "lappend cmd -{flag} ${id}").unwrap();
                } else {
                    writeln!(
                        body,
                        "if {{${id} ne \"\"}} {{ lappend cmd -{flag} ${id} }}"
                    )
                    .unwrap();
                }
            }
            ArgKind::Positional => {
                if arg.required {
                    writeln!(body, "lappend cmd {{*}}${id}").unwrap();
                } else {
                    writeln!(
                        body,
                        "if {{${id} ne \"\"}} {{ lappend cmd {{*}}${id} }}"
                    )
                    .unwrap();
                }
            }
        }
    }
    writeln!(body, "return [{{*}}$cmd]").unwrap();
    body
}

/// Emit `proc <name> { <args> } { <body> }` with args and body each
/// indented two spaces. Mirrors the helper in `vw_ip::generate`.
fn emit_proc(out: &mut String, name: &str, args: &Doc, body: &str) {
    let args_text = args.to_string();
    writeln!(out, "proc {name} {{").unwrap();
    for line in args_text.lines() {
        if line.is_empty() {
            writeln!(out).unwrap();
        } else {
            writeln!(out, "  {line}").unwrap();
        }
    }
    writeln!(out, "}} {{").unwrap();
    for line in body.lines() {
        if line.is_empty() {
            writeln!(out).unwrap();
        } else {
            writeln!(out, "  {line}").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
}

/// Make doc-comment text safe to embed inside the proc arg-list braces.
///
/// The htcl parser captures a proc's arg list as a braced word and
/// brace-matches it raw (only `{`, `}`, `\` are special); a per-arg
/// `##` doc comment with an unbalanced brace or a stray backslash would
/// corrupt that match. Neutralize the three offenders — braces become
/// parentheses, backslashes become slashes — which keeps the prose
/// legible while guaranteeing the generated wrapper parses.
fn sanitize_doc(s: &str) -> String {
    s.replace('\\', "/")
        .replace('{', "(")
        .replace('}', ")")
        .trim_end()
        .to_string()
}
