use iddqd::{bi_upcast, BiHashItem};
use oxide::types::InstanceState;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// An environment is a collection of instances that work together
/// to build, analyze and test vw designs.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct Environment {
    /// The name of this environment.
    pub name: String,
    /// The images this environment's instances boot from, chosen when the
    /// environment was created.
    ///
    /// Absent when the service has no Oxide backend configured, in which case
    /// the environment is a bare record that will never be provisioned.
    pub images: Option<EnvironmentImages>,
    /// The Oxide instance id for the vivado instance.
    pub vivado_instance: Option<OxideInstance>,
    /// The Oxide instance id for the helios instance.
    pub helios_instance: Option<OxideInstance>,
    /// The Oxide instance id for the artifact instance.
    pub artifact_instance: Option<OxideInstance>,
}

/// The images each of an environment's instances boots from.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct EnvironmentImages {
    /// Image the vivado instance boots from.
    pub vivado: ImageRef,
    /// Image the helios instance boots from.
    pub helios: ImageRef,
    /// Image the artifact instance boots from.
    pub artifact: ImageRef,
}

/// An Oxide image an environment's instances are built from.
///
/// Pinned by id, so publishing a newer image does not silently change what an
/// existing environment boots. The name is carried along for display.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct ImageRef {
    pub id: Uuid,
    pub name: String,
}

/// Information about an Oxide instance that underpins a VW instance.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct OxideInstance {
    /// The Oxide instance id, once the control plane has assigned one.
    ///
    /// Absent in the window between asking for an instance and hearing back
    /// about it, which is long enough to be worth showing: an environment
    /// mid-creation reports `creating` with no id rather than looking like
    /// nothing has happened.
    pub id: Option<Uuid>,
    pub state: InstanceState,
    /// The address to reach this instance on, once it has one.
    ///
    /// Absent until the instance exists and the control plane has attached an
    /// external address to it.
    pub external_ip: Option<std::net::IpAddr>,
}

/// Body of a request to create an environment.
///
/// Every field is optional; an image left unset is resolved to the newest
/// image the service can see whose name matches that instance kind's
/// convention. An image named here must already exist, or the request is
/// rejected.
#[derive(Clone, Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct EnvironmentCreate {
    /// Name of the image the vivado instance should boot from.
    #[serde(default)]
    pub vivado_image: Option<String>,
    /// Name of the image the helios instance should boot from.
    #[serde(default)]
    pub helios_image: Option<String>,
    /// Name of the image the artifact instance should boot from.
    #[serde(default)]
    pub artifact_image: Option<String>,
}

/// The ssh keypair that opens an environment's instances.
///
/// Generated by the service when the environment is created and handed out
/// only to the environment's owner.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct SshKeyPair {
    /// The private key, in OpenSSH format, ready to pass to `ssh -i`.
    pub private_key: String,
    /// The matching public key, as it appears in an `authorized_keys` file.
    pub public_key: String,
}

/// Path parameters used to identify an environment in the user API.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct EnvironmentPathParam {
    /// The name of this environment to create.
    pub name: String,
}

/// An environment together with the owner's username.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct UserEnvironment {
    /// User the environment belongs to
    pub user: String,
    /// Environment info
    pub environment: Environment,
}

/// Path parameters used to identify an environment in the admin API.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct UserEnvironmentPathParam {
    /// User the environment belongs to
    pub user: String,
    /// The name of this environment to create.
    pub name: String,
}

impl BiHashItem for UserEnvironment {
    type K1<'a> = &'a str;
    type K2<'a> = &'a str;

    fn key1(&self) -> Self::K1<'_> {
        self.user.as_str()
    }

    fn key2(&self) -> Self::K2<'_> {
        self.environment.name.as_str()
    }

    bi_upcast!();
}
