// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! Scaffold generator for mixed-signal bridge crates.
//!
//! Generates a complete Rust crate in the bench directory that bridges
//! NVC (VHDL simulator) and Xyce (SPICE simulator) via VHPI.

use std::path::Path;
use std::{fs, io::Write};

use proc_macro2::Literal;
use quote::{format_ident, quote};

use crate::{MistConfig, ToolsConfig, VwError};

/// The Xyce FFI wrapper (verbatim from the mist prototype).
const XYCE_RS: &str = include_str!("bridge_assets/xyce.rs");

/// The C++ shim implementing the xyce_* C interface.
const XYCE_CINTERFACE_CPP: &str =
    include_str!("bridge_assets/xyce_cinterface.cpp");

/// Generate or regenerate scaffold files in a bench directory.
///
/// Files that are always regenerated (derived from mist.toml):
/// - `Cargo.toml`, `build.rs`, `xyce_cinterface.cpp`
/// - `src/xyce.rs`, `src/generated.rs`
///
/// Files created only if missing (user-owned):
/// - `src/lib.rs`
pub fn generate_scaffold(
    bench_dir: &Path,
    mist_config: &MistConfig,
    tools: &Option<ToolsConfig>,
) -> crate::Result<()> {
    let src_dir = bench_dir.join("src");
    fs::create_dir_all(&src_dir)?;

    let bench_name = bench_dir
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();

    // Resolve tool paths with defaults
    let xyce_prefix = tools
        .as_ref()
        .and_then(|t| t.xyce.as_ref())
        .map(|x| expand_tilde(&x.prefix))
        .unwrap_or_else(|| {
            let home = std::env::var("HOME").unwrap_or_default();
            format!("{home}/.local/xyce")
        });

    let trilinos_prefix = tools
        .as_ref()
        .and_then(|t| t.xyce.as_ref())
        .map(|x| expand_tilde(&x.trilinos_prefix))
        .unwrap_or_else(|| {
            let home = std::env::var("HOME").unwrap_or_default();
            format!("{home}/.local/trilinos")
        });

    let rust_cosim_path = tools
        .as_ref()
        .and_then(|t| t.rust_cosim.as_ref())
        .map(|r| expand_tilde(&r.path))
        .unwrap_or_else(|| {
            let home = std::env::var("HOME").unwrap_or_default();
            format!("{home}/src/rust-cosim")
        });

    // Always regenerated files
    write_cargo_toml(bench_dir, &bench_name, &rust_cosim_path)?;
    write_build_rs(bench_dir, &xyce_prefix, &trilinos_prefix)?;
    write_file(bench_dir.join("xyce_cinterface.cpp"), XYCE_CINTERFACE_CPP)?;
    write_file(src_dir.join("xyce.rs"), XYCE_RS)?;
    write_generated_rs(&src_dir, mist_config)?;

    // User-owned files (only if missing)
    let lib_rs = src_dir.join("lib.rs");
    if !lib_rs.exists() {
        write_template_lib_rs(&src_dir, mist_config)?;
    }

    write_gitignore(bench_dir)?;

    Ok(())
}

fn write_gitignore(bench_dir: &Path) -> crate::Result<()> {
    let content = "\
# Auto-generated by `vw test --scaffold` — safe to regenerate.
# These files are derived from mist.toml and [tools] config.
Cargo.toml
build.rs
xyce_cinterface.cpp
src/xyce.rs
src/generated.rs

# Build artifacts
/target/
/output/
*.prn
";
    write_file(bench_dir.join(".gitignore"), content)
}

fn expand_tilde(path: &str) -> String {
    if let Some(rest) = path.strip_prefix("~/") {
        let home = std::env::var("HOME").unwrap_or_default();
        format!("{home}/{rest}")
    } else {
        path.to_string()
    }
}

fn write_file(path: impl AsRef<Path>, content: &str) -> crate::Result<()> {
    let mut f = fs::File::create(path.as_ref())?;
    f.write_all(content.as_bytes())?;
    Ok(())
}

fn write_cargo_toml(
    bench_dir: &Path,
    name: &str,
    rust_cosim_path: &str,
) -> crate::Result<()> {
    let content = format!(
        r#"# Auto-generated by `vw test --scaffold` — safe to regenerate.
[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0"

[dependencies]
rust-cosim = {{ path = "{rust_cosim_path}" }}
"#
    );
    write_file(bench_dir.join("Cargo.toml"), &content)
}

fn write_build_rs(
    bench_dir: &Path,
    xyce_prefix: &str,
    trilinos_prefix: &str,
) -> crate::Result<()> {
    let content = format!(
        r#"// Auto-generated by `vw test --scaffold` — safe to regenerate.
fn main() {{
    let xyce_prefix = "{xyce_prefix}";
    let trilinos_prefix = "{trilinos_prefix}";

    // Compile the C++ shim that provides the xyce_* C interface.
    cc::Build::new()
        .cpp(true)
        .file("xyce_cinterface.cpp")
        .include(format!("{{xyce_prefix}}/include"))
        .include(format!("{{trilinos_prefix}}/include"))
        .flag("-std=c++17")
        .compile("xyce_cinterface");

    // Xyce static library
    println!("cargo:rustc-link-search=native={{xyce_prefix}}/lib");
    println!("cargo:rustc-link-lib=static=xyce");

    // Trilinos static libraries
    println!("cargo:rustc-link-search=native={{trilinos_prefix}}/lib");

    println!("cargo:rustc-link-arg=-Wl,--start-group");

    let trilinos_libs = [
        "trilinoscouplings",
        "rol",
        "stokhos",
        "stokhos_sacado",
        "stokhos_amesos2",
        "stokhos_amesos2_mp_16_serial",
        "stokhos_tpetra",
        "stokhos_tpetra_mp_16_serial",
        "stokhos_tpetra_pce_serial",
        "stokhos_tpetraext_mp_16_serial",
        "stokhos_tpetraext_pce_serial",
        "stokhos_tpetra_sd_mp_16_serial",
        "stokhos_tpetra_sd_pce_serial",
        "nox",
        "noxepetra",
        "noxlapack",
        "loca",
        "locaepetra",
        "localapack",
        "amesos2",
        "belos",
        "belosepetra",
        "belostpetra",
        "ifpack",
        "amesos",
        "aztecoo",
        "trilinosss",
        "tpetra",
        "tpetraclassic",
        "tpetraext",
        "tpetrainout",
        "epetra",
        "epetraext",
        "triutils",
        "sacado",
        "kokkoskernels",
        "kokkoscontainers",
        "kokkoscore",
        "kokkossimd",
        "teuchoscomm",
        "teuchoscore",
        "teuchoskokkoscomm",
        "teuchoskokkoscompat",
        "teuchosnumerics",
        "teuchosparameterlist",
        "teuchosparser",
        "teuchosremainder",
    ];

    for lib in &trilinos_libs {{
        println!("cargo:rustc-link-lib=static={{lib}}");
    }}

    println!("cargo:rustc-link-arg=-Wl,--end-group");

    // System dependencies
    println!("cargo:rustc-link-lib=dylib=fftw3");
    println!("cargo:rustc-link-lib=dylib=dl");
    println!("cargo:rustc-link-lib=dylib=stdc++");
    println!("cargo:rustc-link-lib=dylib=gfortran");
    println!("cargo:rustc-link-lib=dylib=m");
    println!("cargo:rustc-link-lib=dylib=quadmath");
    println!("cargo:rustc-link-lib=dylib=lapack");
    println!("cargo:rustc-link-lib=dylib=blas");

    // SuiteSparse (transitive deps of Trilinos sparse solvers)
    println!("cargo:rustc-link-lib=dylib=amd");
    println!("cargo:rustc-link-lib=dylib=colamd");
    println!("cargo:rustc-link-lib=dylib=suitesparseconfig");
}}
"#
    );
    write_file(bench_dir.join("build.rs"), &content)
}

/// Generate `src/generated.rs` using `quote` and `prettyplease`.
fn write_generated_rs(src_dir: &Path, mist: &MistConfig) -> crate::Result<()> {
    let clock_hz = Literal::f64_unsuffixed(mist.clock);
    let clock_period_val = 1.0 / mist.clock;
    let clock_period = Literal::f64_unsuffixed(clock_period_val);
    let prime_cycles = mist.prime_cycles.unwrap_or(0);

    let netlist_path = &mist.netlist;

    // Build DAC constants
    let mut dac_const_defs = Vec::new();
    let mut port_names_sorted: Vec<&String> = mist.ports.keys().collect();
    port_names_sorted.sort();

    for port_name in &port_names_sorted {
        let mapping = &mist.ports[port_name.as_str()];
        let const_name = format_ident!("{}", mapping.dac.to_uppercase());
        let dac_value = format!("YDAC!{}", mapping.dac.to_uppercase());
        let dac_lit = Literal::string(&dac_value);
        dac_const_defs.push(quote! {
            pub const #const_name: &str = #dac_lit;
        });
    }

    // Build Signals struct fields and constructor
    let mut struct_fields = Vec::new();
    let mut ctor_fields = Vec::new();

    for port_name in &port_names_sorted {
        let field_ident = format_ident!("{}", port_name);
        let port_lit = Literal::string(port_name);
        struct_fields.push(quote! {
            pub #field_ident: SimHandle
        });
        ctor_fields.push(quote! {
            #field_ident: dut.get_child(#port_lit)?
        });
    }

    // Build update_dacs body
    let mut update_stmts = Vec::new();
    for port_name in &port_names_sorted {
        let mapping = &mist.ports[port_name.as_str()];
        let field_ident = format_ident!("{}", port_name);
        let dac_const = format_ident!("{}", mapping.dac.to_uppercase());
        let convert_fn = match mapping.encoding.as_str() {
            "pam4" => format_ident!("binstr_to_pam4"),
            _ => format_ident!("binstr_to_unsigned"),
        };

        update_stmts.push(quote! {
            xyce.update_dac(
                #dac_const,
                &[t],
                &[#convert_fn(&sigs.#field_ident.get_value_binstr().unwrap_or_default())],
            )?;
        });
    }

    let tokens = quote! {
        //! Auto-generated from mist.toml — do not edit.
        //! Re-generate with: `vw test <name> --scaffold`

        #![allow(dead_code)]

        use rust_cosim::handles::SimHandle;
        use rust_cosim::TestError;
        use crate::xyce::Xyce;

        /// Clock frequency in Hz.
        pub const CLOCK_HZ: f64 = #clock_hz;

        /// Clock period in seconds.
        pub const CLOCK_PERIOD: f64 = #clock_period;

        /// Number of pipeline priming cycles.
        pub const PRIME_CYCLES: u32 = #prime_cycles;

        /// Path to the Xyce netlist, relative to the crate root.
        pub const NETLIST: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/", #netlist_path);

        // DAC device names (fully-qualified as they appear in the Xyce netlist)
        #(#dac_const_defs)*

        /// Signal handles for all mapped ports.
        pub struct Signals {
            #(#struct_fields),*
        }

        impl Signals {
            /// Acquire signal handles from the top-level DUT.
            pub fn new(dut: &SimHandle) -> Result<Self, TestError> {
                Ok(Self {
                    #(#ctor_fields),*
                })
            }
        }

        /// Convert a 2-bit PAM4 binary string to a symbol voltage (0.0–3.0).
        pub fn binstr_to_pam4(binstr: &str) -> f64 {
            match binstr {
                "00" => 0.0,
                "01" => 1.0,
                "10" => 2.0,
                "11" => 3.0,
                _ => {
                    eprintln!("warning: unexpected PAM4 binstr '{binstr}', defaulting to 0");
                    0.0
                }
            }
        }

        /// Convert an N-bit binary string to an unsigned integer as f64.
        pub fn binstr_to_unsigned(binstr: &str) -> f64 {
            u64::from_str_radix(binstr, 2).unwrap_or(0) as f64
        }

        /// Read all mapped VHDL ports and update the corresponding Xyce DACs.
        pub fn update_dacs(sigs: &Signals, xyce: &mut Xyce, t: f64) -> Result<(), String> {
            #(#update_stmts)*
            Ok(())
        }
    };

    let file =
        syn::parse2::<syn::File>(tokens).map_err(|e| VwError::CodeGen {
            message: format!("Failed to parse generated code: {e}"),
        })?;
    let formatted = prettyplease::unparse(&file);

    write_file(src_dir.join("generated.rs"), &formatted)
}

/// Generate the template `src/lib.rs` (only written if file doesn't exist).
fn write_template_lib_rs(
    src_dir: &Path,
    mist: &MistConfig,
) -> crate::Result<()> {
    // Half-period in picoseconds, rounded to nearest integer
    let half_period_ps = (0.5e12 / mist.clock).round() as u64;
    let half_period_ps_lit = Literal::u64_unsuffixed(half_period_ps);

    // Build DAC initialization statements
    let mut init_stmts = Vec::new();
    let mut port_names_sorted: Vec<&String> = mist.ports.keys().collect();
    port_names_sorted.sort();

    for port_name in &port_names_sorted {
        let mapping = &mist.ports[port_name.as_str()];
        let dac_const = format_ident!("{}", mapping.dac.to_uppercase());
        init_stmts.push(quote! {
            xyce.update_dac(#dac_const, &[0.0], &[0.0]).map_err(TestError::IoError)?;
        });
    }

    let tokens = quote! {
        //! Mixed-signal testbench.
        //!
        //! This file was scaffolded by `vw test --scaffold` and is yours to edit.
        //! The `generated` module provides DAC constants, signal handles, encoding
        //! helpers, and the `update_dacs()` bulk-update function.

        mod xyce;
        mod generated;

        use rust_cosim::clock::Clock;
        use rust_cosim::executor;
        use rust_cosim::handles::{SetAction, SimHandle};
        use rust_cosim::triggers::{Edge, ReadWrite};
        use rust_cosim::utils::ps;
        use rust_cosim::TestError;
        use std::future::Future;
        use std::path::PathBuf;
        use std::pin::Pin;

        use xyce::Xyce;
        use generated::*;

        #[no_mangle]
        pub fn testbench_main(
            dut: SimHandle,
        ) -> Pin<Box<dyn Future<Output = Result<(), TestError>>>> {
            Box::pin(async move {
                println!("mixed-signal testbench started");

                // Mapped port handles (DAC outputs)
                let sigs = Signals::new(&dut)?;

                // Clock and other input handles (not in port mapping)
                let clk = dut.get_child("clk")?;

                // Initialize Xyce
                let netlist = PathBuf::from(NETLIST);
                let mut xyce = Xyce::new(&netlist).map_err(TestError::IoError)?;

                // Initialize all DACs to zero
                #(#init_stmts)*

                // Start the clock
                executor::spawn(Clock::new(clk, ps(#half_period_ps_lit)).run());

                // Let the simulator propagate initial values
                ReadWrite::new().await;

                // Step Xyce past t=0
                xyce.simulate_until(1e-12).map_err(TestError::IoError)?;

                let mut sim_time: f64 = 0.0;

                // ---- Prime the pipeline ----
                for _ in 0..PRIME_CYCLES {
                    Edge::rising(clk).await;
                    sim_time += CLOCK_PERIOD;
                    update_dacs(&sigs, &mut xyce, sim_time).map_err(TestError::IoError)?;
                    xyce.simulate_until(sim_time + CLOCK_PERIOD * 0.9)
                        .map_err(TestError::IoError)?;
                }

                // ---- Main test logic (program your test here) ----
                for cycle in 0..16u32 {
                    Edge::rising(clk).await;
                    sim_time += CLOCK_PERIOD;

                    update_dacs(&sigs, &mut xyce, sim_time).map_err(TestError::IoError)?;
                    xyce.simulate_until(sim_time + CLOCK_PERIOD * 0.9)
                        .map_err(TestError::IoError)?;

                    let v_p = xyce.get_circuit_value("V(OUT_P)");
                    let v_n = xyce.get_circuit_value("V(OUT_N)");
                    println!(
                        "cycle={cycle:3} V(OUT_P)={v_p:+.4} V(OUT_N)={v_n:+.4} V(diff)={:+.4}",
                        v_p - v_n,
                    );
                }

                println!("mixed-signal testbench complete");
                Ok(())
            })
        }
    };

    let file =
        syn::parse2::<syn::File>(tokens).map_err(|e| VwError::CodeGen {
            message: format!("Failed to parse generated template: {e}"),
        })?;
    let formatted = prettyplease::unparse(&file);

    write_file(src_dir.join("lib.rs"), &formatted)
}
