[package]
name = "vw-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Receives source on a vw build instance"
keywords = ["vhdl", "workspace", "dependency-management"]
categories = ["development-tools"]

[[bin]]
name = "vw-agent"
path = "src/main.rs"

[dependencies]
vw-sync = { path = "../vw-sync" }
vw-remote = { path = "../vw-remote" }
vw-bench = { path = "../vw-bench" }
vw-lib = { path = "../vw-lib" }
rust-s3 = { version = "0.37", default-features = false, features = ["with-tokio"] }
blake3 = "1"
rand = "0.8"
reqwest = { version = "0.13", features = ["json"] }
serde.workspace = true
serde_json.workspace = true
tokio-tungstenite.workspace = true
vw-sync-api = { path = "../vw-sync-api" }
vw-api-types-versions = { path = "../vw-api-types/versions" }
camino.workspace = true
clap.workspace = true
dropshot.workspace = true
thiserror.workspace = true
tokio.workspace = true
slog = "2.8.2"
slog-bunyan = "2.5.0"
slog-async = "2.8.0"
slog-error-chain = { git = "https://github.com/oxidecomputer/slog-error-chain", branch = "main" }

[dev-dependencies]
tempfile.workspace = true
vw-sync = { path = "../vw-sync" }
vw-remote = { path = "../vw-remote" }
tokio-tungstenite.workspace = true
serde_json.workspace = true
